# Association Rules

In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder


from mlxtend.frequent_patterns import apriori, association_rules

from pyECLAT import ECLAT

In [2]:
cluster_1 = pd.read_csv('clusters/cluster_1.csv')
cluster_2 = pd.read_csv('clusters/cluster_2.csv')
cluster_3 = pd.read_csv('clusters/cluster_3.csv')
cluster_4 = pd.read_csv('clusters/cluster_4.csv')
cluster_5 = pd.read_csv('clusters/cluster_5.csv')
cluster_6 = pd.read_csv('clusters/cluster_6.csv')
cluster_7 = pd.read_csv('clusters/cluster_7.csv')
cluster_8 = pd.read_csv('clusters/cluster_8.csv')
cluster_9 = pd.read_csv('clusters/cluster_9.csv')

Adding a label 'cluster' to link each customer to each number of cluster and 'type_of_customer' to have the characteristics of the group that the customer belongs:

In [3]:
cluster_1['type_of_customer'] = 'Vegan People'
cluster_2['type_of_customer'] = 'High Spenders'
cluster_3['type_of_customer'] = 'Young Families with Issues'
cluster_4['type_of_customer'] = 'Loyal Stable Shoppers'
cluster_5['type_of_customer'] = 'Tech-Gamer Customers'
cluster_6['type_of_customer'] = 'University Low-Spenders'
cluster_7['type_of_customer'] = 'Hygiene Obsessed'
cluster_8['type_of_customer'] = 'Loyal Average Spenders'
cluster_9['type_of_customer'] = 'Big Family'

In [4]:
datasets = [cluster_1, cluster_2, cluster_3, cluster_4, cluster_5, cluster_6, cluster_7, cluster_8, cluster_9]

scored_customers = combined_dataset = pd.concat(datasets)
scored_customers.drop(columns=['kids_home', 'teens_home', 'number_complaints', 'distinct_stores_visited', 'lifetime_spend_groceries', 'lifetime_spend_electronics', 'typical_hour', 'lifetime_spend_vegetables', 'lifetime_spend_nonalcohol_drinks', 'lifetime_spend_alcohol_drinks', 'lifetime_spend_meat', 'lifetime_spend_fish', 'lifetime_spend_hygiene', 'lifetime_spend_videogames', 'lifetime_spend_petfood', 'lifetime_total_distinct_products', 'loyalty_card_number', 'customer_age', 'years_since_first_transaction'], inplace=True)
scored_customers.to_csv('scored_customers.csv', index=True)

In [5]:
scored_customers

      customer_id type_of_customer
0           22853     Vegan People
1             994     Vegan People
2           29221     Vegan People
3            1818     Vegan People
4            7272     Vegan People
...           ...              ...
1434        25714       Big Family
1435         1030       Big Family
1436         5852       Big Family
1437        14274       Big Family
1438        38012       Big Family

[33862 rows x 2 columns]

In [6]:
cluster_1.set_index('customer_id', inplace=True)
cluster_2.set_index('customer_id', inplace=True)
cluster_3.set_index('customer_id', inplace=True)
cluster_4.set_index('customer_id', inplace=True)
cluster_5.set_index('customer_id', inplace=True)
cluster_6.set_index('customer_id', inplace=True)
cluster_7.set_index('customer_id', inplace=True)
cluster_8.set_index('customer_id', inplace=True)
cluster_9.set_index('customer_id', inplace=True)

In [7]:
dataset_basket = pd.read_csv('data/customer_basket.csv').set_index('customer_id')

In [8]:
import ast

# Convert the string representation of lists to actual lists
dataset_basket['list_of_goods'] = dataset_basket['list_of_goods'].apply(ast.literal_eval)

In [9]:
cluster_1_basket = dataset_basket[dataset_basket.index.isin(cluster_1.index)]
cluster_2_basket = dataset_basket[dataset_basket.index.isin(cluster_2.index)]
cluster_3_basket = dataset_basket[dataset_basket.index.isin(cluster_3.index)]
cluster_4_basket = dataset_basket[dataset_basket.index.isin(cluster_4.index)]
cluster_5_basket = dataset_basket[dataset_basket.index.isin(cluster_5.index)]
cluster_6_basket = dataset_basket[dataset_basket.index.isin(cluster_6.index)]
cluster_7_basket = dataset_basket[dataset_basket.index.isin(cluster_7.index)]
cluster_8_basket = dataset_basket[dataset_basket.index.isin(cluster_8.index)]
cluster_9_basket = dataset_basket[dataset_basket.index.isin(cluster_9.index)]
cluster_1_basket

             invoice_id                                      list_of_goods
customer_id
5902            7188908  [avocado, portal, pet food, ratchet & clank 3,...
20070          11588714  [pickles, mashed potato, asparagus, vegetables...
28051          10500042  [black beer, shallot, eggplant, flax seed, asp...
21585           1786347  [meatballs, megaman zero 3, frozen vegetables,...
31512            326870    [vacuum cleaner, tomatoes, herb & pepper, beer]
...                 ...                                                ...
30081           1889450  [deodorant, toothpaste, carrots, melons, tomat...
27606           3441932  [yams, tooth brush, shallot, cotton buds, poke...
23771           6850385  [shallot, oatmeal, mashed potato, cottage chee...
20657           7027893  [meatballs, mashed potato, frozen smoothie, as...
19691          10387390  [cake, antioxydant juice, honey, toothpaste, t...

[13522 rows x 2 columns]

----

To understand which promotions and offers can be made for **each cluster of customers** we applied **Apriori algorithm**:

## Cluster 1 - **Vegan People**

In [10]:
te = TransactionEncoder()
te_fit = te.fit(cluster_1_basket['list_of_goods']).transform(cluster_1_basket['list_of_goods'])
dataset_cluster_1_basket = pd.DataFrame(te_fit, columns=te.columns_)

dataset_cluster_1_basket

,airpods,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,beer,black beer,...,vacuum cleaner,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,True,True,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False,...,False,True,True,False,False,False,False,False,False,False
2,False,True,False,True,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13517,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13518,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
13519,False,False,False,True,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13520,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13521,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

## Apriori algorithm

'support' will tell us the most popular items that are bought by the customers of this cluster

Below it we can see the item(s) that is(are) bought together with the most popular items calculated by 'support' (sorted by the higher confidence to the lower)

In [11]:
frequent_itemsets = apriori(dataset_cluster_1_basket, min_support=0.05, use_colnames=True)
display(frequent_itemsets.sort_values(by='support', ascending=False))

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6, num_itemsets=100)
rules = rules.sort_values(by='confidence', ascending=False)

display(rules.head(50).sort_values(by='confidence', ascending=False))

      support                          itemsets
30   0.782503                        (tomatoes)
0    0.657151                       (asparagus)
5    0.554652                         (carrots)
54   0.537642             (asparagus, tomatoes)
76   0.457625               (carrots, tomatoes)
..        ...                               ...
58   0.051620          (mashed potato, avocado)
120  0.051546  (asparagus, carrots, shower gel)
91   0.050880             (green beans, melons)
72   0.050362                  (razor, carrots)
94   0.050067                   (ham, tomatoes)

[175 rows x 2 columns]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
191,"(shallot, asparagus, carrots)",(tomatoes),0.060716,0.782503,0.054208,0.892814,1.140972,1.0,0.006698,2.029152,0.131541,0.068704,0.507183,0.481044
195,"(asparagus, carrots, zucchini)",(tomatoes),0.075063,0.782503,0.066410,0.884729,1.130640,1.0,0.007673,1.886837,0.124923,0.083941,0.470012,0.484799
187,"(asparagus, carrots, melons)",(tomatoes),0.112483,0.782503,0.099246,0.882314,1.127554,1.0,0.011227,1.848120,0.127462,0.124721,0.458910,0.504573
202,"(mashed potato, asparagus, melons)",(tomatoes),0.070774,0.782503,0.061899,0.874608,1.117706,1.0,0.006519,1.734542,0.113332,0.078217,0.423479,0.476856
168,"(cauliflower, carrots, asparagus)",(tomatoes),0.091776,0.782503,0.080240,0.874295,1.117306,1.0,0.008424,1.730220,0.115599,0.101052,0.422039,0.488419
153,"(carrots, toothpaste)",(tomatoes),0.071291,0.782503,0.062269,0.873444,1.116219,1.0,0.006483,1.718586,0.112111,0.078670,0.418126,0.476510
171,"(asparagus, carrots, flax seed)",(tomatoes),0.059163,0.782503,0.051620,0.872500,1.115012,1.0,0.005325,1.705862,0.109635,0.065337,0.413786,0.469234
175,"(asparagus, carrots, frozen vegetables)",(tomatoes),0.097988,0.782503,0.085490,0.872453,1.114952,1.0,0.008814,1.705231,0.114301,0.107535,0.413569,0.490853
160,"(mashed potato, green beans)",(tomatoes),0.065597,0.782503,0.057166,0.871477,1.113705,1.0,0.005836,1.692282,0.109263,0.072277,0.409082,0.472266
116,"(shallot, asparagus)",(tomatoes),0.094661,0.782503,0.082310,0.869531,1.111218,1.0,0.008238,1.667046,0.110552,0.103554,0.400137,0.487360
183,"(mashed potato, asparagus, carrots)",(tomatoes),0.154119,0.782503,0.133930,0.869002,1.110542,1.0,0.013331,1.660310,0.117675,0.166851,0.397703,0.520079
179,"(asparagus, carrots, green beans)",(tomatoes),0.077725,0.782503,0.067446,0.867745,1.108936,1.0,0.006625,1.644531,0.106513,0.085075,0.391924,0.476969
205,"(mashed potato, carrots, melons)",(tomatoes),0.060272,0.782503,0.052285,0.867485,1.108603,1.0,0.005122,1.641300,0.104247,0.066143,0.390727,0.467151
199,"(mashed potato, asparagus, frozen vegetables)",(tomatoes),0.062195,0.782503,0.053838,0.865636,1.106241,1.0,0.005170,1.618720,0.102407,0.068076,0.382228,0.467219
133,"(carrots, cologne)",(tomatoes),0.061529,0.782503,0.053247,0.865385,1.105919,1.0,0.005100,1.615695,0.102054,0.067334,0.381071,0.466716
126,"(asparagus, zucchini)",(tomatoes),0.119435,0.782503,0.103313,0.865015,1.105447,1.0,0.009855,1.611277,0.108327,0.129364,0.379374,0.498522
147,"(shallot, carrots)",(tomatoes),0.082828,0.782503,0.071587,0.864286,1.104515,1.0,0.006774,1.602613,0.103171,0.090189,0.376019,0.477885
145,"(carrots, melons)",(tomatoes),0.155524,0.782503,0.134226,0.863053,1.102939,1.0,0.012528,1.588184,0.110520,0.166989,0.370350,0.517293
162,"(mashed potato, zucchini)",(tomatoes),0.061751,0.782503,0.053247,0.862275,1.101946,1.0,0.004926,1.579220,0.098603,0.067315,0.366776,0.465161
155,"(carrots, zucchini)",(tomatoes),0.100355,0.782503,0.086304,0.859985,1.099019,1.0,0.007776,1.553389,0.100148,0.108346,0.356246,0.485139
106,"(green grapes, asparagus)",(tomatoes),0.064709,0.782503,0.055613,0.859429,1.098308,1.0,0.004978,1.547238,0.095701,0.070254,0.353687,0.465250
124,"(asparagus, toothpaste)",(tomatoes),0.084085,0.782503,0.072253,0.859279,1.098116,1.0,0.006456,1.545591,0.097552,0.090960,0.352998,0.475807
131,"(cauliflower, carrots)",(tomatoes),0.120322,0.782503,0.103313,0.858636,1.097294,1.0,0.009161,1.538558,0.100795,0.129220,0.350041,0.495332
91,"(cauliflower, asparagus)",(tomatoes),0.142656,0.782503,0.122319,0.857439,1.095765,1.0,0.010690,1.525645,0.101938,0.152358,0.344540,0.506879
119,"(asparagus, shower gel)",(tomatoes),0.081719,0.782503,0.070034,0.857014,1.095221,1.0,0.006089,1.521105,0.094680,0.088183,0.342583,0.473257
140,"(carrots, green beans)",(tomatoes),0.107898,0.782503,0.092442,0.856751,1.094886,1.0,0.008011,1.518319,0.097145,0.115848,0.341377,0.487444
161,"(mashed potato, melons)",(tomatoes),0.096879,0.782503,0.082976,0.856489,1.094550,1.0,0.007168,1.515540,0.095649,0.104188,0.340169,0.481264
101,"(asparagus, frozen vegetables)",(tomatoes),0.157817,0.782503,0.134965,0.855201,1.092906,1.0,0.011473,1.502070,0.100938,0.167585,0.334252,0.513840
143,"(mashed potato, carrots)",(tomatoes),0.210694,0.782503,0.179855,0.853633,1.090901,1.0,0.014987,1.485972,0.105569,0.221131,0.327040,0.541739
149,"(carrots, shower gel)",(tomatoes),0.071143,0.782503,0.060716,0.853430,1.090642,1.0,0.005046,1.483919,0.089475,0.076572,0.326109,0.465511
82,"(asparagus, carrots)",(tomatoes),0.389218,0.782503,0.331756,0.852366,1.089281,1.0,0.027192,1.473216,0.134194,0.394964,0.321213,0.638167
95,"(cotton buds, asparagus)",(tomatoes),0.060938,0.782503,0.051915,0.851942,1.088740,1.0,0.004231,1.468999,0.086796,0.065589,0.319264,0.459144
112,"(mashed potato, asparagus)",(tomatoes),0.244638,0.782503,0.208327,0.851572,1.088267,1.0,0.016897,1.465339,0.107376,0.254426,0.317564,0.558902
114,"(asparagus, melons)",(tomatoes),0.180003,0.782503,0.153232,0.851274,1.087886,1.0,0.012379,1.462400,0.098520,0.189345,0.316192,0.523548
159,"(frozen vegetables, melons)",(tomatoes),0.063082,0.782503,0.053616,0.849941,1.086183,1.0,0.004254,1.449416,0.084688,0.067700,0.310067,0.459230
163,"(asparagus, carrots, avocado)",(tomatoes),0.065893,0.782503,0.055983,0.849607,1.085756,1.0,0.004422,1.446195,0.084555,0.070649,0.308531,0.460575
129,"(carrots, avocado)",(tomatoes),0.087043,0.782503,0.073806,0.847918,1.083598,1.0,0.005694,1.430137,0.084504,0.092751,0.300766,0.471119
97,"(asparagus, flax seed)",(tomatoes),0.094291,0.782503,0.079870,0.847059,1.082500,1.0,0.006087,1.422098,0.084146,0.100223,0.296814,0.474564
135,"(carrots, flax seed)",(tomatoes),0.079278,0.782503,0.067150,0.847015,1.082444,1.0,0.005114,1.421690,0.082722,0.084504,0.296612,0.466415
138,"(frozen vegetables, carrots)",(tomatoes),0.133486,0.782503,0.113001,0.846537,1.081833,1.0,0.008548,1.417267,0.087296,0.140726,0.294416,0.495474
104,"(asparagus, green beans)",(tomatoes),0.124982,0.782503,0.105606,0.844970,1.079831,1.0,0.007807,1.402941,0.084489,0.131698,0.287212,0.489965
157,"(mashed potato, cauliflower)",(tomatoes),0.076172,0.782503,0.064266,0.843689,1.078194,1.0,0.004661,1.391443,0.078503,0.080897,0.281322,0.462909
93,"(asparagus, cologne)",(tomatoes),0.071883,0.782503,0.060642,0.843621,1.078107,1.0,0.004393,1.390839,0.078059,0.076400,0.281009,0.460559
151,"(carrots, strawberries)",(tomatoes),0.065967,0.782503,0.055613,0.843049,1.077376,1.0,0.003994,1.385769,0.076891,0.070143,0.278379,0.457060
158,"(mashed potato, frozen vegetables)",(tomatoes),0.086526,0.782503,0.072918,0.842735,1.076974,1.0,0.005212,1.383000,0.078243,0.091593,0.276934,0.467960
63,"(asparagus, avocado)",(tomatoes),0.102574,0.782503,0.086378,0.842105,1.076169,1.0,0.006114,1.377484,0.078868,0.108148,0.274039,0.476246
59,(toothpaste),(tomatoes),0.121136,0.782503,0.101908,0.841270,1.075102,1.0,0.007119,1.370234,0.079484,0.127110,0.270197,0.485752
25,(body spray),(tomatoes),0.068925,0.782503,0.057832,0.839056,1.072272,1.0,0.003898,1.351384,0.072391,0.072873,0.260018,0.456481
49,(hot dogs),(tomatoes),0.082384,0.782503,0.068999,0.837522,1.070313,1.0,0.004533,1.338630,0.071592,0.086694,0.252968,0.462850
54,(shallot),(tomatoes),0.136296,0.782503,0.114036,0.836679,1.069235,1.0,0.007384,1.331720,0.074970,0.141702,0.249091,0.491206

Associations with more than 1 item:

In [12]:
frequent_itemsets_2 = apriori(
    dataset_cluster_1_basket, min_support=0.02, use_colnames=True
    )

rules_2 = association_rules(frequent_itemsets_2,
                                  metric="confidence",
                                  min_threshold=0.2, num_itemsets=100)

rules_2.sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1876,"(cauliflower, tomatoes, frozen vegetables)","(carrots, asparagus)",0.040748,0.389218,0.021594,0.529946,1.361566,1.0,0.005734,1.299387,0.276832,0.052879,0.230406,0.292714
2028,"(carrots, zucchini)","(asparagus, tomatoes, melons)",0.100355,0.153232,0.020929,0.208548,1.360999,1.0,0.005551,1.069892,0.294834,0.089955,0.065327,0.172566
1583,"(shallot, asparagus)","(frozen vegetables, tomatoes)",0.094661,0.184144,0.023591,0.249219,1.353388,1.0,0.006160,1.086676,0.288415,0.092437,0.079762,0.188666
2029,"(zucchini, melons)","(carrots, tomatoes, asparagus)",0.046665,0.331756,0.020929,0.448494,1.351882,1.0,0.005448,1.211673,0.273031,0.058544,0.174695,0.255790
2002,"(shallot, asparagus)","(mashed potato, carrots, tomatoes)",0.094661,0.179855,0.023000,0.242969,1.350914,1.0,0.005974,1.083370,0.286921,0.091444,0.076954,0.185424
1881,"(cauliflower, frozen vegetables)","(carrots, tomatoes, asparagus)",0.048218,0.331756,0.021594,0.447853,1.349948,1.0,0.005598,1.210265,0.272363,0.060256,0.173735,0.256472
2022,"(carrots, zucchini, tomatoes)","(asparagus, melons)",0.086304,0.180003,0.020929,0.242502,1.347212,1.0,0.005394,1.082507,0.282070,0.085292,0.076219,0.179386
2023,"(zucchini, tomatoes, melons)","(carrots, asparagus)",0.040157,0.389218,0.020929,0.521179,1.339042,1.0,0.005299,1.275596,0.263790,0.051240,0.216052,0.287475
1880,"(asparagus, carrots, frozen vegetables)","(cauliflower, tomatoes)",0.097988,0.164695,0.021594,0.220377,1.338097,1.0,0.005456,1.071423,0.280119,0.089571,0.066662,0.175748
2001,"(shallot, carrots)","(mashed potato, asparagus, tomatoes)",0.082828,0.208327,0.023000,0.277679,1.332897,1.0,0.005744,1.096012,0.272309,0.085769,0.087601,0.194040

----

## Cluster 2 - **High Spenders**

In [13]:
te = TransactionEncoder()
te_fit = te.fit(cluster_2_basket['list_of_goods']).transform(cluster_2_basket['list_of_goods'])
dataset_cluster_2_basket = pd.DataFrame(te_fit, columns=te.columns_)

dataset_cluster_2_basket

,airpods,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,beer,black beer,...,vacuum cleaner,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11900,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
11901,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11902,True,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,True
11903,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11904,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

## Apriori algorithm

In [14]:
frequent_itemsets = apriori(dataset_cluster_2_basket, min_support=0.05, use_colnames=True)
display(frequent_itemsets.sort_values(by='support', ascending=False))

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6, num_itemsets=100)
rules = rules.sort_values(by='confidence', ascending=False)

display(rules.head(50).sort_values(by='confidence', ascending=False))

      support                                       itemsets
7    0.762705                                    (champagne)
12   0.549517                                   (fresh tuna)
69   0.453591                        (champagne, fresh tuna)
5    0.429399                         (bluetooth headphones)
53   0.356405              (bluetooth headphones, champagne)
..        ...                                            ...
109  0.051071     (bluetooth headphones, champagne, almonds)
152  0.050819  (cottage cheese, fresh tuna, frozen smoothie)
133  0.050483     (bluetooth headphones, salmon, fresh tuna)
111  0.050315             (fresh tuna, asparagus, champagne)
139  0.050147           (french wine, champagne, fresh tuna)

[162 rows x 2 columns]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
69,"(cottage cheese, frozen smoothie)",(champagne),0.076438,0.762705,0.067955,0.889011,1.165603,1.0,0.009655,2.138007,0.153834,0.088117,0.532275,0.489054
109,"(fresh tuna, frozen smoothie, spaghetti)",(champagne),0.073415,0.762705,0.065183,0.887872,1.164110,1.0,0.009189,2.116286,0.152144,0.084550,0.527474,0.486667
103,"(bluetooth headphones, fresh tuna, frozen smoo...",(champagne),0.088198,0.762705,0.078202,0.886667,1.162529,1.0,0.010933,2.093782,0.153330,0.101207,0.522395,0.494600
101,"(bluetooth headphones, cottage cheese, fresh t...",(champagne),0.069635,0.762705,0.061739,0.886610,1.162456,1.0,0.008628,2.092742,0.150212,0.080118,0.522158,0.483779
92,"(salmon, spaghetti)",(champagne),0.062495,0.762705,0.055271,0.884409,1.159569,1.0,0.007606,2.052880,0.146784,0.071787,0.512879,0.478438
56,"(bluetooth headphones, fromage blanc)",(champagne),0.068123,0.762705,0.060143,0.882861,1.157539,1.0,0.008185,2.025752,0.146048,0.078038,0.506356,0.480858
74,"(fresh tuna, fromage blanc)",(champagne),0.088870,0.762705,0.078370,0.881853,1.156217,1.0,0.010589,2.008467,0.148289,0.101358,0.502108,0.492303
50,"(blueberries, bluetooth headphones)",(champagne),0.061403,0.762705,0.053927,0.878249,1.151493,1.0,0.007095,1.949021,0.140169,0.070019,0.486922,0.474477
90,"(frozen smoothie, spaghetti)",(champagne),0.110458,0.762705,0.096850,0.876806,1.149601,1.0,0.012603,1.926193,0.146292,0.124757,0.480841,0.501894
57,"(bluetooth headphones, frozen smoothie)",(champagne),0.136077,0.762705,0.119026,0.874691,1.146828,1.0,0.015239,1.893686,0.148196,0.152645,0.471929,0.515374
107,"(bluetooth headphones, fresh tuna, spaghetti)",(champagne),0.105082,0.762705,0.091894,0.874500,1.146578,1.0,0.011748,1.890805,0.142850,0.118437,0.471125,0.497492
70,"(cottage cheese, spaghetti)",(champagne),0.082990,0.762705,0.072575,0.874494,1.146569,1.0,0.009277,1.890707,0.139402,0.093872,0.471097,0.484824
97,"(bluetooth headphones, fresh tuna, avocado)",(champagne),0.077866,0.762705,0.068039,0.873786,1.145642,1.0,0.008650,1.880109,0.137862,0.088072,0.468116,0.481497
51,"(blueberries, fresh tuna)",(champagne),0.078790,0.762705,0.068795,0.873134,1.144787,1.0,0.008701,1.870445,0.137292,0.089031,0.465368,0.481666
68,"(fresh tuna, cottage cheese)",(champagne),0.135321,0.762705,0.118102,0.872750,1.144283,1.0,0.014891,1.864793,0.145823,0.151427,0.463748,0.513798
46,"(frozen smoothie, avocado)",(champagne),0.083998,0.762705,0.073247,0.872000,1.143300,1.0,0.009181,1.853869,0.136832,0.094700,0.460588,0.484018
43,"(cottage cheese, avocado)",(champagne),0.064763,0.762705,0.056447,0.871595,1.142769,1.0,0.007052,1.848027,0.133584,0.073211,0.458882,0.472802
38,"(fresh tuna, almonds)",(champagne),0.072407,0.762705,0.063083,0.871230,1.142290,1.0,0.007858,1.842779,0.134289,0.081710,0.457341,0.476969
60,"(bluetooth headphones, salmon)",(champagne),0.078454,0.762705,0.068207,0.869379,1.139863,1.0,0.008369,1.816670,0.133148,0.088242,0.449542,0.479403
78,"(grated cheese, fresh tuna)",(champagne),0.064091,0.762705,0.055607,0.867628,1.137567,1.0,0.006725,1.792636,0.129212,0.072105,0.442162,0.470268
47,"(spaghetti, avocado)",(champagne),0.095170,0.762705,0.082402,0.865843,1.135227,1.0,0.009816,1.768786,0.131648,0.106261,0.434641,0.486941
99,"(fresh tuna, avocado, spaghetti)",(champagne),0.060647,0.762705,0.052499,0.865651,1.134975,1.0,0.006243,1.766260,0.126601,0.068105,0.433832,0.467242
82,"(iphone 10, fresh tuna)",(champagne),0.083410,0.762705,0.072155,0.865055,1.134194,1.0,0.008537,1.758464,0.129084,0.093228,0.431322,0.479829
53,"(bluetooth headphones, cottage cheese)",(champagne),0.106258,0.762705,0.091894,0.864822,1.133888,1.0,0.010851,1.755430,0.132118,0.118257,0.430339,0.492653
80,"(fresh tuna, iMac)",(champagne),0.065603,0.762705,0.056699,0.864277,1.133173,1.0,0.006663,1.748374,0.125773,0.073481,0.428040,0.469308
105,"(bluetooth headphones, fresh tuna, laptop)",(champagne),0.061739,0.762705,0.053255,0.862585,1.130955,1.0,0.006166,1.726852,0.123411,0.069056,0.420911,0.466204
88,"(fresh tuna, spaghetti)",(champagne),0.209240,0.762705,0.180428,0.862304,1.130587,1.0,0.020840,1.723331,0.146067,0.227953,0.419728,0.549434
61,"(bluetooth headphones, spaghetti)",(champagne),0.162117,0.762705,0.139773,0.862176,1.130419,1.0,0.016126,1.721729,0.137695,0.178044,0.419188,0.522718
76,"(fresh tuna, frozen smoothie)",(champagne),0.178916,0.762705,0.154221,0.861972,1.130151,1.0,0.017761,1.719180,0.140257,0.195861,0.418327,0.532087
91,"(laptop, spaghetti)",(champagne),0.075430,0.762705,0.065015,0.861915,1.130077,1.0,0.007484,1.718477,0.124496,0.084094,0.418089,0.473579
55,"(bluetooth headphones, fresh tuna)",(champagne),0.262831,0.762705,0.226207,0.860658,1.128429,1.0,0.025745,1.702974,0.154391,0.282997,0.412792,0.578622
84,"(fresh tuna, laptop)",(champagne),0.122050,0.762705,0.104998,0.860289,1.127945,1.0,0.011910,1.698473,0.129201,0.134655,0.411236,0.498977
72,"(french wine, fresh tuna)",(champagne),0.058295,0.762705,0.050147,0.860231,1.127868,1.0,0.005685,1.697762,0.120390,0.065054,0.410989,0.462990
37,"(bluetooth headphones, almonds)",(champagne),0.059387,0.762705,0.051071,0.859972,1.127529,1.0,0.005776,1.694624,0.120246,0.066238,0.409898,0.463466
41,"(bluetooth headphones, avocado)",(champagne),0.120958,0.762705,0.103906,0.859028,1.126291,1.0,0.011651,1.683277,0.127560,0.133254,0.405921,0.497631
58,"(bluetooth headphones, iphone 10)",(champagne),0.069887,0.762705,0.059891,0.856971,1.123595,1.0,0.006588,1.659073,0.118265,0.077508,0.397254,0.467748
40,"(asparagus, fresh tuna)",(champagne),0.058715,0.762705,0.050315,0.856938,1.123552,1.0,0.005533,1.658694,0.116825,0.065251,0.397116,0.461454
89,"(frozen smoothie, laptop)",(champagne),0.065015,0.762705,0.055691,0.856589,1.123094,1.0,0.006104,1.654653,0.117224,0.072136,0.395644,0.464803
86,"(salmon, fresh tuna)",(champagne),0.097270,0.762705,0.082990,0.853195,1.118644,1.0,0.008802,1.616399,0.117489,0.106811,0.381341,0.481003
45,"(fresh tuna, avocado)",(champagne),0.154389,0.762705,0.131709,0.853101,1.118521,1.0,0.013956,1.615365,0.125308,0.167701,0.380945,0.512894
21,(nonfat milk),(champagne),0.095338,0.762705,0.081142,0.851101,1.115899,1.0,0.008428,1.593669,0.114807,0.104444,0.372517,0.478744
59,"(bluetooth headphones, laptop)",(champagne),0.096094,0.762705,0.081730,0.850524,1.115142,1.0,0.008439,1.587519,0.114230,0.105178,0.370086,0.478842
13,(fromage blanc),(champagne),0.143301,0.762705,0.120790,0.842907,1.105156,1.0,0.011493,1.510544,0.111066,0.153830,0.337987,0.500639
14,(frozen smoothie),(champagne),0.285594,0.762705,0.240655,0.842647,1.104814,1.0,0.022831,1.508045,0.132796,0.297972,0.336890,0.579088
9,(cottage cheese),(champagne),0.218396,0.762705,0.183788,0.841538,1.103361,1.0,0.017217,1.497494,0.119854,0.230510,0.332218,0.541254
4,(blueberries),(champagne),0.128685,0.762705,0.107938,0.838773,1.099735,1.0,0.009789,1.471807,0.104084,0.137772,0.320563,0.490146
16,(ground beef),(champagne),0.066695,0.762705,0.055775,0.836272,1.096456,1.0,0.004907,1.449326,0.094257,0.072096,0.310024,0.454700
27,(spaghetti),(champagne),0.338177,0.762705,0.282402,0.835072,1.094882,1.0,0.024473,1.438781,0.130941,0.345033,0.304967,0.602668
8,(brownies),(champagne),0.086770,0.762705,0.072407,0.834463,1.094084,1.0,0.006226,1.433485,0.094164,0.093179,0.302400,0.464698
2,(avocado),(champagne),0.250651,0.762705,0.208820,0.833110,1.092310,1.0,0.017647,1.421866,0.112776,0.259553,0.296699,0.553449

Associations with more than 1 item:

In [15]:
frequent_itemsets_2 = apriori(
    dataset_cluster_2_basket, min_support=0.02, use_colnames=True
    )

rules_2 = association_rules(frequent_itemsets_2,
                                  metric="confidence",
                                  min_threshold=0.2, num_itemsets=100)

rules_2.sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1601,"(cottage cheese, spaghetti)","(champagne, frozen smoothie)",0.082990,0.240655,0.028727,0.346154,1.438381,1.0,0.008755,1.161351,0.332356,0.097408,0.138934,0.232763
1731,"(salmon, spaghetti)","(champagne, frozen smoothie)",0.062495,0.240655,0.021588,0.345430,1.435374,1.0,0.006548,1.160067,0.323537,0.076671,0.137981,0.217567
1737,"(cottage cheese, spaghetti)","(fresh tuna, frozen smoothie)",0.082990,0.178916,0.021252,0.256073,1.431243,1.0,0.006403,1.103715,0.328575,0.088307,0.093969,0.187426
1790,"(bluetooth headphones, fresh tuna, frozen smoo...","(cottage cheese, champagne)",0.088198,0.183788,0.023100,0.261905,1.425035,1.0,0.006890,1.105835,0.327114,0.092811,0.095706,0.193795
1602,"(frozen smoothie, spaghetti)","(champagne, cottage cheese)",0.110458,0.183788,0.028727,0.260076,1.415085,1.0,0.008427,1.103102,0.329752,0.108194,0.093466,0.208192
1792,"(bluetooth headphones, cottage cheese)","(fresh tuna, champagne, frozen smoothie)",0.106258,0.154221,0.023100,0.217391,1.409610,1.0,0.006712,1.080718,0.325132,0.097311,0.074689,0.183587
1786,"(bluetooth headphones, cottage cheese, champagne)","(fresh tuna, frozen smoothie)",0.091894,0.178916,0.023100,0.251371,1.404964,1.0,0.006658,1.096783,0.317406,0.093252,0.088243,0.190240
1733,"(fresh tuna, cottage cheese, spaghetti)",(frozen smoothie),0.053171,0.285594,0.021252,0.399684,1.399482,1.0,0.006066,1.190050,0.301480,0.066931,0.159699,0.237048
1570,"(fresh tuna, cottage cheese)","(champagne, frozen smoothie)",0.135321,0.240655,0.045443,0.335816,1.395425,1.0,0.012877,1.143275,0.327720,0.137484,0.125320,0.262323
1228,"(frozen smoothie, avocado)","(champagne, cottage cheese)",0.083998,0.183788,0.021504,0.256000,1.392907,1.0,0.006066,1.097059,0.307944,0.087312,0.088472,0.186501

-----

## Cluster 3 - **Young Famalies with Issues**

In [16]:
te = TransactionEncoder()
te_fit = te.fit(cluster_3_basket['list_of_goods']).transform(cluster_3_basket['list_of_goods'])
dataset_cluster_3_basket = pd.DataFrame(te_fit, columns=te.columns_)

dataset_cluster_3_basket

,airpods,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,beer,black beer,...,vacuum cleaner,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,True,False,...,False,False,True,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8595,False,False,False,True,False,False,False,False,True,False,...,False,True,False,False,False,False,False,False,False,False
8596,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8597,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8598,False,False,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
8599,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

## Apriori algorithm

In [17]:
frequent_itemsets = apriori(dataset_cluster_3_basket, min_support=0.05, use_colnames=True)
display(frequent_itemsets.sort_values(by='support', ascending=False))

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6, num_itemsets=100)
rules = rules.sort_values(by='confidence', ascending=False)

display(rules.head(50).sort_values(by='confidence', ascending=False))

      support                            itemsets
26   0.788256                               (oil)
9    0.566860                       (cooking oil)
85   0.467093                  (cooking oil, oil)
3    0.430000                              (cake)
61   0.358256                         (cake, oil)
..        ...                                 ...
165  0.051163  (cooking oil, cake, tomatoes, oil)
107  0.050814                        (salad, oil)
122  0.050581           (asparagus, carrots, oil)
81   0.050233                  (ham, cooking oil)
131  0.050233        (cooking oil, cake, carrots)

[168 rows x 2 columns]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
99,"(asparagus, cake, cooking oil)",(oil),0.082209,0.788256,0.072442,0.881188,1.117896,1.0,0.007640,1.782180,0.114909,0.090777,0.438890,0.486545
51,"(asparagus, carrots)",(oil),0.057558,0.788256,0.050581,0.878788,1.114851,1.0,0.005211,1.746890,0.109311,0.063606,0.427554,0.471478
101,"(asparagus, cooking oil, candy bars)",(oil),0.066512,0.788256,0.058372,0.877622,1.113373,1.0,0.005944,1.730252,0.109083,0.073295,0.422050,0.475837
61,"(carrots, cake)",(oil),0.078953,0.788256,0.069186,0.876289,1.111681,1.0,0.006951,1.711599,0.109073,0.086697,0.415751,0.482030
113,"(cooking oil, soup, candy bars)",(oil),0.060116,0.788256,0.052674,0.876209,1.111579,1.0,0.005287,1.710496,0.106800,0.066199,0.415374,0.471516
95,"(cooking oil, vegetables mix)",(oil),0.076279,0.788256,0.066512,0.871951,1.106178,1.0,0.006384,1.653621,0.103913,0.083345,0.395267,0.478165
56,"(asparagus, soup)",(oil),0.073721,0.788256,0.064070,0.869085,1.102542,1.0,0.005959,1.617419,0.100407,0.080297,0.381731,0.475183
81,"(cooking oil, carrots)",(oil),0.103372,0.788256,0.089767,0.868391,1.101662,1.0,0.008284,1.608894,0.102920,0.111949,0.378455,0.491136
57,"(asparagus, tomatoes)",(oil),0.064651,0.788256,0.056047,0.866906,1.099778,1.0,0.005085,1.590943,0.096997,0.070334,0.371442,0.469004
107,"(cooking oil, soup, cake)",(oil),0.072209,0.788256,0.062558,0.866345,1.099065,1.0,0.005639,1.584255,0.097151,0.078403,0.368788,0.472854
103,"(cooking oil, cake, candy bars)",(oil),0.107674,0.788256,0.093140,0.865011,1.097373,1.0,0.008265,1.568601,0.099440,0.116020,0.362489,0.491585
109,"(cooking oil, cake, tomatoes)",(oil),0.059186,0.788256,0.051163,0.864440,1.096649,1.0,0.004509,1.561997,0.093676,0.064252,0.359794,0.464673
67,"(cake, french fries)",(oil),0.060814,0.788256,0.052558,0.864245,1.096401,1.0,0.004621,1.559749,0.093619,0.065985,0.358871,0.465461
105,"(napkins, cooking oil, cake)",(oil),0.088023,0.788256,0.075930,0.862616,1.094335,1.0,0.006545,1.541253,0.094523,0.094871,0.351177,0.479471
73,"(carrots, candy bars)",(oil),0.063372,0.788256,0.054651,0.862385,1.094042,1.0,0.004698,1.538674,0.091775,0.068573,0.350090,0.465859
75,"(cooking oil, candy bars)",(oil),0.211279,0.788256,0.182093,0.861860,1.093376,1.0,0.015551,1.532825,0.108279,0.222760,0.347610,0.546434
53,"(asparagus, cooking oil)",(oil),0.162093,0.788256,0.139535,0.860832,1.092072,1.0,0.011764,1.521502,0.100619,0.172092,0.342755,0.518925
80,"(candy bars, tomatoes)",(oil),0.070698,0.788256,0.060814,0.860197,1.091267,1.0,0.005086,1.514594,0.089996,0.076195,0.339757,0.468674
83,"(cooking oil, french fries)",(oil),0.083953,0.788256,0.072209,0.860111,1.091157,1.0,0.006032,1.513656,0.091198,0.090262,0.339348,0.475859
50,"(asparagus, candy bars)",(oil),0.102674,0.788256,0.088256,0.859570,1.090470,1.0,0.007322,1.507824,0.092458,0.109952,0.336792,0.485767
63,"(cooking oil, cake)",(oil),0.265698,0.788256,0.228023,0.858206,1.088740,1.0,0.018586,1.493319,0.110999,0.276081,0.330351,0.573741
91,"(cooking oil, soup)",(oil),0.147442,0.788256,0.126512,0.858044,1.088535,1.0,0.010290,1.491620,0.095400,0.156344,0.329588,0.509270
48,"(asparagus, cake)",(oil),0.125000,0.788256,0.107093,0.856744,1.086886,1.0,0.008561,1.478084,0.091360,0.132843,0.323449,0.496302
93,"(cooking oil, tomatoes)",(oil),0.116163,0.788256,0.099419,0.855856,1.085759,1.0,0.007853,1.468975,0.089366,0.123501,0.319253,0.490990
85,"(cooking oil, fresh bread)",(oil),0.080349,0.788256,0.068721,0.855282,1.085031,1.0,0.005385,1.463152,0.085214,0.085914,0.316544,0.471232
111,"(napkins, cooking oil, candy bars)",(oil),0.069651,0.788256,0.059535,0.854758,1.084366,1.0,0.004632,1.457871,0.083627,0.074570,0.314068,0.465143
30,(meatballs),(oil),0.090349,0.788256,0.077209,0.854569,1.084126,1.0,0.005991,1.455976,0.085305,0.096344,0.313175,0.476259
69,"(napkins, cake)",(oil),0.132791,0.788256,0.113372,0.853765,1.083107,1.0,0.008699,1.447975,0.088479,0.140369,0.309380,0.498796
71,"(cake, tomatoes)",(oil),0.091279,0.788256,0.077907,0.853503,1.082774,1.0,0.005956,1.445384,0.084125,0.097186,0.308142,0.476169
87,"(mint, cooking oil)",(oil),0.071512,0.788256,0.060930,0.852033,1.080909,1.0,0.004561,1.431018,0.080618,0.076274,0.301197,0.464665
55,"(napkins, asparagus)",(oil),0.087093,0.788256,0.074186,0.851802,1.080617,1.0,0.005534,1.428796,0.081720,0.092598,0.300110,0.472958
89,"(napkins, cooking oil)",(oil),0.176047,0.788256,0.149767,0.850727,1.079252,1.0,0.010998,1.418499,0.089122,0.183869,0.295029,0.520363
72,"(cake, vegetables mix)",(oil),0.061279,0.788256,0.052093,0.850095,1.078450,1.0,0.003789,1.412521,0.077492,0.065325,0.292046,0.458091
98,"(napkins, tomatoes)",(oil),0.065000,0.788256,0.055233,0.849732,1.077990,1.0,0.003996,1.409107,0.077377,0.069212,0.290331,0.459900
11,(carrots),(oil),0.166395,0.788256,0.140930,0.846960,1.074474,1.0,0.009768,1.383589,0.083147,0.173192,0.277242,0.512874
42,(sparkling water),(oil),0.065814,0.788256,0.055698,0.846290,1.073623,1.0,0.003819,1.377554,0.073406,0.069764,0.274076,0.458475
59,"(cake, candy bars)",(oil),0.165233,0.788256,0.139419,0.843772,1.070429,1.0,0.009173,1.355354,0.078819,0.171261,0.262185,0.510321
79,"(soup, candy bars)",(oil),0.092558,0.788256,0.078023,0.842965,1.069405,1.0,0.005064,1.348387,0.071521,0.097190,0.258373,0.470973
34,(muffins),(oil),0.073488,0.788256,0.061860,0.841772,1.067892,1.0,0.003933,1.338223,0.068618,0.077337,0.252741,0.460125
70,"(soup, cake)",(oil),0.113140,0.788256,0.095116,0.840699,1.066531,1.0,0.005933,1.329207,0.070338,0.117969,0.247672,0.480683
44,(turkey),(oil),0.079535,0.788256,0.066860,0.840643,1.066460,1.0,0.004167,1.328743,0.067703,0.083479,0.247409,0.462732
45,(vegetables mix),(oil),0.123837,0.788256,0.104070,0.840376,1.066120,1.0,0.006454,1.326515,0.070785,0.128796,0.246145,0.486200
97,"(napkins, soup)",(oil),0.076047,0.788256,0.063837,0.839450,1.064946,1.0,0.003893,1.318864,0.066004,0.079750,0.241772,0.460217
78,"(napkins, candy bars)",(oil),0.105581,0.788256,0.088605,0.839207,1.064638,1.0,0.005380,1.316875,0.067880,0.110036,0.240626,0.475807
39,(soda),(oil),0.072791,0.788256,0.060814,0.835463,1.059888,1.0,0.003436,1.286911,0.060940,0.075995,0.222946,0.456307
31,(milk),(oil),0.069767,0.788256,0.058256,0.835000,1.059301,1.0,0.003261,1.283298,0.060180,0.072841,0.220758,0.454452
46,(yogurt cake),(oil),0.079419,0.788256,0.066279,0.834553,1.058734,1.0,0.003677,1.279834,0.060262,0.082705,0.218649,0.459318
23,(escalope),(oil),0.079070,0.788256,0.065930,0.833824,1.057808,1.0,0.003603,1.274213,0.059341,0.082269,0.215202,0.458732
3,(bacon),(oil),0.093605,0.788256,0.078023,0.833540,1.057449,1.0,0.004239,1.272045,0.059938,0.097064,0.213864,0.466261
7,(cake),(oil),0.430000,0.788256,0.358256,0.833153,1.056958,1.0,0.019306,1.269092,0.094541,0.416577,0.212035,0.643822

Associations with more than 1 item:

In [18]:
frequent_itemsets_2 = apriori(
    dataset_cluster_3_basket, min_support=0.02, use_colnames=True
    )

rules_2 = association_rules(frequent_itemsets_2,
                                  metric="confidence",
                                  min_threshold=0.2, num_itemsets=100)

rules_2.sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1201,"(mint, oil)","(asparagus, cake)",0.097558,0.125000,0.020698,0.212157,1.697259,1.0,0.008503,1.110628,0.455226,0.102535,0.099608,0.188869
1200,"(mint, cake)","(asparagus, oil)",0.056977,0.221860,0.020698,0.363265,1.637359,1.0,0.008057,1.222078,0.412779,0.080180,0.181722,0.228278
344,(mint),"(asparagus, cake)",0.117907,0.125000,0.023721,0.201183,1.609467,1.0,0.008983,1.095370,0.429293,0.108223,0.087067,0.195475
1198,"(mint, cake, oil)",(asparagus),0.048721,0.267093,0.020698,0.424821,1.590536,1.0,0.007685,1.274224,0.390297,0.070134,0.215209,0.251157
343,"(mint, cake)",(asparagus),0.056977,0.267093,0.023721,0.416327,1.558732,1.0,0.008503,1.255680,0.380110,0.078978,0.203619,0.252569
1195,"(cake, tomatoes)","(asparagus, cooking oil)",0.091279,0.162093,0.022907,0.250955,1.548218,1.0,0.008111,1.118634,0.389665,0.099395,0.106053,0.196138
1327,"(napkins, asparagus)","(tomatoes, oil)",0.087093,0.159884,0.021512,0.246996,1.544848,1.0,0.007587,1.115686,0.386334,0.095410,0.103691,0.190771
1324,"(napkins, asparagus, oil)",(tomatoes),0.074186,0.192442,0.021512,0.289969,1.506786,1.0,0.007235,1.137356,0.363286,0.087761,0.120768,0.200876
1640,"(olive oil, oil)","(cooking oil, candy bars)",0.068372,0.211279,0.021744,0.318027,1.505247,1.0,0.007299,1.156528,0.360291,0.084310,0.135343,0.210472
1328,"(napkins, tomatoes)","(asparagus, oil)",0.065000,0.221860,0.021512,0.330948,1.491695,1.0,0.007091,1.163048,0.352536,0.081069,0.140190,0.213954

---

## Cluster 4 - **Loyal Stable Shoppers**

In [19]:
te = TransactionEncoder()
te_fit = te.fit(cluster_1_basket['list_of_goods']).transform(cluster_4_basket['list_of_goods'])
dataset_cluster_4_basket = pd.DataFrame(te_fit, columns=te.columns_)

dataset_cluster_4_basket

,airpods,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,beer,black beer,...,vacuum cleaner,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16748,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16749,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16750,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
16751,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
16752,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False

## Apriori algorithm

In [20]:
frequent_itemsets = apriori(dataset_cluster_4_basket, min_support=0.05, use_colnames=True)
display(frequent_itemsets.sort_values(by='support', ascending=False))

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6, num_itemsets=100)
rules = rules.sort_values(by='confidence', ascending=False)

display(rules.head(50).sort_values(by='confidence', ascending=False))

      support                          itemsets
21   0.765475                             (oil)
7    0.533994                     (cooking oil)
31   0.529040                             (tea)
75   0.427088                (cooking oil, oil)
110  0.425297                        (tea, oil)
..        ...                               ...
165  0.050558      (cooking oil, pet food, oil)
180  0.050439              (tea, pet food, oil)
107  0.050319                   (sandwich, oil)
153  0.050081  (cooking oil, tea, french fries)
148  0.050081        (candy bars, tea, muffins)

[196 rows x 2 columns]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
102,"(tea, cake, candy bars)",(oil),0.087686,0.765475,0.076524,0.872703,1.140080,1.0,0.009402,1.842339,0.134678,0.098532,0.457212,0.486336
108,"(cooking oil, tea, cake)",(oil),0.139557,0.765475,0.120158,0.860992,1.124782,1.0,0.013330,1.687138,0.128932,0.153091,0.407280,0.508982
88,"(milk, tea)",(oil),0.059392,0.765475,0.051095,0.860302,1.123880,1.0,0.005632,1.678795,0.117185,0.066034,0.404335,0.463526
121,"(cooking oil, tea, muffins)",(oil),0.081896,0.765475,0.070375,0.859329,1.122610,1.0,0.007686,1.667194,0.118961,0.090574,0.400190,0.475633
115,"(cooking oil, tea, candy bars)",(oil),0.113233,0.765475,0.097296,0.859251,1.122508,1.0,0.010619,1.666271,0.123074,0.124513,0.399857,0.493178
98,"(cooking oil, cake, candy bars)",(oil),0.083746,0.765475,0.071868,0.858161,1.121083,1.0,0.007762,1.653461,0.117877,0.092452,0.395208,0.476024
113,"(tea, cake, muffins)",(oil),0.064526,0.765475,0.055333,0.857539,1.120271,1.0,0.005941,1.646245,0.114764,0.071429,0.392557,0.464913
45,"(cake, olive oil)",(oil),0.059094,0.765475,0.050618,0.856566,1.118999,1.0,0.005383,1.635070,0.113023,0.065402,0.388405,0.461346
124,"(napkins, cooking oil, tea)",(oil),0.071151,0.765475,0.060885,0.855705,1.117874,1.0,0.006420,1.625314,0.113522,0.078486,0.384734,0.467622
44,"(napkins, cake)",(oil),0.094132,0.765475,0.080404,0.854153,1.115848,1.0,0.008348,1.608027,0.114609,0.103187,0.378120,0.479595
41,"(ketchup, cake)",(oil),0.059750,0.765475,0.051036,0.854146,1.115838,1.0,0.005298,1.607943,0.110410,0.065921,0.378087,0.460409
106,"(cooking oil, cake, muffins)",(oil),0.063750,0.765475,0.054438,0.853933,1.115559,1.0,0.005639,1.605595,0.110642,0.070262,0.377178,0.462525
67,"(milk, cooking oil)",(oil),0.059870,0.765475,0.051095,0.853440,1.114915,1.0,0.005266,1.600195,0.109635,0.065993,0.375076,0.460095
38,"(cake, fresh bread)",(oil),0.069182,0.765475,0.058855,0.850733,1.111380,1.0,0.005898,1.571183,0.107666,0.075864,0.363537,0.463810
111,"(tea, cake, gums)",(oil),0.074673,0.765475,0.063451,0.849720,1.110056,1.0,0.006291,1.560590,0.107146,0.081694,0.359217,0.466306
95,"(tea, pet food)",(oil),0.059452,0.765475,0.050439,0.848394,1.108323,1.0,0.004930,1.546934,0.103914,0.065125,0.353560,0.457143
104,"(cooking oil, gums, cake)",(oil),0.075927,0.765475,0.064347,0.847484,1.107135,1.0,0.006227,1.537711,0.104719,0.082808,0.349683,0.465773
83,"(gums, muffins)",(oil),0.070972,0.765475,0.059930,0.844407,1.103115,1.0,0.005602,1.507300,0.100618,0.077177,0.336562,0.461349
57,"(tea, candy bars)",(oil),0.188086,0.765475,0.158778,0.844176,1.102814,1.0,0.014803,1.505069,0.114826,0.199775,0.335579,0.525800
127,"(cooking oil, tea, soup)",(oil),0.064287,0.765475,0.054259,0.844011,1.102598,1.0,0.005049,1.503474,0.099444,0.069966,0.334874,0.457447
92,"(napkins, tea)",(oil),0.119322,0.765475,0.100698,0.843922,1.102482,1.0,0.009360,1.502615,0.105550,0.128426,0.334493,0.487736
75,"(cooking oil, pet food)",(oil),0.059930,0.765475,0.050558,0.843625,1.102094,1.0,0.004684,1.499766,0.098542,0.065249,0.333229,0.454837
47,"(tea, cake)",(oil),0.233809,0.765475,0.196860,0.841971,1.099933,1.0,0.017885,1.484063,0.118578,0.245332,0.326174,0.549572
31,"(cake, candy bars)",(oil),0.142303,0.765475,0.119740,0.841443,1.099243,1.0,0.010810,1.479122,0.105262,0.151947,0.323923,0.498934
97,"(tea, yogurt cake)",(oil),0.066197,0.765475,0.055692,0.841298,1.099054,1.0,0.005019,1.477775,0.096516,0.071769,0.323307,0.457026
42,"(cake, muffins)",(oil),0.105235,0.765475,0.088521,0.841180,1.098899,1.0,0.007967,1.476671,0.100583,0.113172,0.322801,0.478411
96,"(tea, soup)",(oil),0.105712,0.765475,0.088820,0.840203,1.097624,1.0,0.007900,1.467647,0.099454,0.113527,0.318637,0.478118
46,"(soup, cake)",(oil),0.080702,0.765475,0.067749,0.839497,1.096701,1.0,0.005974,1.461189,0.095915,0.087033,0.315626,0.464001
90,"(tea, muffins)",(oil),0.135797,0.765475,0.113950,0.839121,1.096210,1.0,0.010001,1.457773,0.101557,0.144731,0.314022,0.493991
39,"(gums, cake)",(oil),0.123142,0.765475,0.103325,0.839069,1.096142,1.0,0.009063,1.457305,0.100027,0.131575,0.313802,0.487025
35,"(cooking oil, cake)",(oil),0.232496,0.765475,0.195070,0.839024,1.096084,1.0,0.017100,1.456899,0.114215,0.242956,0.313610,0.546930
60,"(cooking oil, fresh bread)",(oil),0.095983,0.765475,0.080404,0.837687,1.094336,1.0,0.006931,1.444891,0.095356,0.102942,0.307906,0.471362
55,"(napkins, candy bars)",(oil),0.074852,0.765475,0.062675,0.837321,1.093858,1.0,0.005378,1.441640,0.092747,0.080596,0.306346,0.459599
82,"(tea, fresh bread)",(oil),0.095983,0.765475,0.080344,0.837065,1.093523,1.0,0.006871,1.439376,0.094605,0.102858,0.305254,0.471012
48,"(cooking oil, candy bars)",(oil),0.185997,0.765475,0.155674,0.836970,1.093400,1.0,0.013298,1.438544,0.104941,0.195620,0.304853,0.520170
37,"(cake, french fries)",(oil),0.068286,0.765475,0.057124,0.836538,1.092836,1.0,0.004853,1.434742,0.091176,0.073553,0.303011,0.455582
73,"(napkins, cooking oil)",(oil),0.121172,0.765475,0.101295,0.835961,1.092081,1.0,0.008541,1.429688,0.095943,0.128981,0.300547,0.484145
78,"(cooking oil, yogurt cake)",(oil),0.066794,0.765475,0.055811,0.835567,1.091568,1.0,0.004682,1.426270,0.089890,0.071879,0.298870,0.454239
84,"(napkins, gums)",(oil),0.063869,0.765475,0.053364,0.835514,1.091498,1.0,0.004473,1.425806,0.089547,0.068769,0.298642,0.452614
69,"(cooking oil, muffins)",(oil),0.135438,0.765475,0.113114,0.835170,1.091048,1.0,0.009439,1.422828,0.096523,0.143582,0.297174,0.491470
76,"(cooking oil, soup)",(oil),0.106847,0.765475,0.089178,0.834637,1.090352,1.0,0.007390,1.418243,0.092778,0.113872,0.294902,0.475569
86,"(tea, ketchup)",(oil),0.080463,0.765475,0.067152,0.834570,1.090264,1.0,0.005560,1.417668,0.090036,0.086227,0.294616,0.461148
59,"(cooking oil, french fries)",(oil),0.087387,0.765475,0.072763,0.832650,1.087757,1.0,0.005870,1.401407,0.088402,0.093274,0.286432,0.463853
118,"(cooking oil, tea, gums)",(oil),0.097833,0.765475,0.081359,0.831605,1.086391,1.0,0.006470,1.392706,0.088144,0.104046,0.281973,0.468945
93,"(tea, olive oil)",(oil),0.077658,0.765475,0.064526,0.830899,1.085469,1.0,0.005081,1.386897,0.085369,0.082873,0.278966,0.457597
81,"(tea, french fries)",(oil),0.085418,0.765475,0.070972,0.830887,1.085454,1.0,0.005587,1.386800,0.086079,0.091000,0.278915,0.461802
53,"(muffins, candy bars)",(oil),0.081179,0.765475,0.067451,0.830882,1.085447,1.0,0.005310,1.386757,0.085676,0.086564,0.278893,0.459499
77,"(cooking oil, tea)",(oil),0.303170,0.765475,0.251776,0.830478,1.084919,1.0,0.019707,1.383453,0.112326,0.308221,0.277171,0.579696
85,"(tea, gums)",(oil),0.158658,0.765475,0.131678,0.829947,1.084225,1.0,0.010229,1.379132,0.092332,0.166165,0.274906,0.500984
29,"(tea, babies food)",(oil),0.066257,0.765475,0.054916,0.828829,1.082764,1.0,0.004198,1.370121,0.081862,0.070693,0.270137,0.450285

Associations with more than 1 item:

In [21]:
frequent_itemsets_2 = apriori(
    dataset_cluster_4_basket, min_support=0.02, use_colnames=True
    )

rules_2 = association_rules(frequent_itemsets_2,
                                  metric="confidence",
                                  min_threshold=0.2, num_itemsets=100)

rules_2.sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1659,"(gums, muffins)","(tea, cake)",0.070972,0.233809,0.022921,0.322960,1.381301,1.0,0.006327,1.131679,0.297133,0.081321,0.116357,0.210497
2229,"(tea, olive oil)","(muffins, oil)",0.077658,0.187787,0.020116,0.259032,1.379388,1.0,0.005533,1.096150,0.298198,0.081995,0.087716,0.183076
1499,"(gums, muffins)","(cooking oil, cake)",0.070972,0.232496,0.022742,0.320437,1.378251,1.0,0.006241,1.129409,0.295408,0.081012,0.114581,0.209128
2398,"(fresh bread, candy bars)","(cooking oil, tea, oil)",0.057900,0.251776,0.020056,0.346392,1.375794,1.0,0.005478,1.144759,0.289934,0.069250,0.126454,0.213025
2324,"(cake, fresh bread)","(cooking oil, tea, oil)",0.069182,0.251776,0.023936,0.345988,1.374191,1.0,0.006518,1.144053,0.292537,0.080587,0.125914,0.220528
1658,"(cake, muffins)","(tea, gums)",0.105235,0.158658,0.022921,0.217811,1.372829,1.0,0.006225,1.075624,0.303518,0.095120,0.070307,0.181140
2394,"(fresh bread, candy bars, oil)","(cooking oil, tea)",0.048469,0.303170,0.020056,0.413793,1.364890,1.0,0.005362,1.188711,0.280958,0.060486,0.158752,0.239974
1500,"(cake, muffins)","(cooking oil, gums)",0.105235,0.159554,0.022742,0.216109,1.354460,1.0,0.005952,1.072147,0.292477,0.093958,0.067292,0.179323
2464,"(gums, muffins)","(cooking oil, tea, oil)",0.070972,0.251776,0.024175,0.340622,1.352880,1.0,0.006306,1.134743,0.280762,0.080968,0.118743,0.218320
2458,"(cooking oil, muffins, oil)","(tea, gums)",0.113114,0.158658,0.024175,0.213720,1.347049,1.0,0.006228,1.070029,0.290496,0.097637,0.065446,0.183045

-----

## Cluster 5 - **Tech-Gamer Customers**

In [22]:
te = TransactionEncoder()
te_fit = te.fit(cluster_5_basket['list_of_goods']).transform(cluster_5_basket['list_of_goods'])
dataset_cluster_5_basket = pd.DataFrame(te_fit, columns=te.columns_)

dataset_cluster_5_basket

,airpods,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,beer,black beer,...,vacuum cleaner,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10771,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,True
10772,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
10773,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10774,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10775,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

## Apriori algorithm

In [23]:
frequent_itemsets = apriori(dataset_cluster_5_basket, min_support=0.05, use_colnames=True)
display(frequent_itemsets.sort_values(by='support', ascending=False))

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6, num_itemsets=100)
rules = rules.sort_values(by='confidence', ascending=False)

display(rules.head(50).sort_values(by='confidence', ascending=False))

      support                                           itemsets
11   0.585932                                     (energy drink)
22   0.425019                                         (pancakes)
73   0.346325                           (energy drink, pancakes)
28   0.328415                                      (protein bar)
14   0.297420                      (gadget for tiktok streaming)
..        ...                                                ...
130  0.051132  (airpods, gadget for tiktok streaming, pancake...
80   0.050761                            (french wine, pancakes)
54   0.050761                                 (champagne, cider)
96   0.050204                      (protein bar, metroid fusion)
123  0.050019                   (energy drink, pancakes, laptop)

[134 rows x 2 columns]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
66,"(protein bar, pancakes, energy bar)",(energy drink),0.065794,0.585932,0.058556,0.889986,1.518924,1.0,0.020005,3.763775,0.365700,0.098717,0.734309,0.494961
46,"(pancakes, iPad)",(energy drink),0.062361,0.585932,0.054751,0.877976,1.498428,1.0,0.018212,3.393340,0.354757,0.092245,0.705305,0.485710
67,"(protein bar, gadget for tiktok streaming, pan...",(energy drink),0.078879,0.585932,0.069042,0.875294,1.493850,1.0,0.022825,3.320359,0.358898,0.115888,0.698828,0.496564
34,"(protein bar, energy bar)",(energy drink),0.103842,0.585932,0.090664,0.873101,1.490107,1.0,0.029820,3.262975,0.367019,0.151332,0.693531,0.513918
31,"(energy bar, gadget for tiktok streaming)",(energy drink),0.080271,0.585932,0.070063,0.872832,1.489649,1.0,0.023030,3.256083,0.357389,0.117528,0.692882,0.496204
41,"(half-life 2, pancakes)",(energy drink),0.070341,0.585932,0.061340,0.872032,1.488282,1.0,0.020125,3.235709,0.352908,0.103104,0.690949,0.488360
61,"(airpods, gadget for tiktok streaming, pancakes)",(energy drink),0.058742,0.585932,0.051132,0.870458,1.485597,1.0,0.016714,3.196405,0.347269,0.086148,0.687149,0.478862
33,"(energy bar, pancakes)",(energy drink),0.129918,0.585932,0.112287,0.864286,1.475062,1.0,0.036163,3.051030,0.370152,0.186039,0.672242,0.527962
64,"(airpods, protein bar, pancakes)",(energy drink),0.073589,0.585932,0.063567,0.863808,1.474247,1.0,0.020449,3.040335,0.347241,0.106665,0.671089,0.486149
47,"(iphone 10, pancakes)",(energy drink),0.101800,0.585932,0.087602,0.860529,1.468650,1.0,0.027954,2.968843,0.355269,0.145972,0.663168,0.505019
57,"(protein bar, pancakes)",(energy drink),0.196826,0.585932,0.169079,0.859029,1.466090,1.0,0.053753,2.937254,0.395822,0.275518,0.659546,0.573797
43,"(pancakes, iMac)",(energy drink),0.089551,0.585932,0.076745,0.856995,1.462619,1.0,0.024274,2.895478,0.347405,0.128177,0.654634,0.493987
51,"(pancakes, laptop)",(energy drink),0.058463,0.585932,0.050019,0.855556,1.460163,1.0,0.015763,2.866627,0.334713,0.084153,0.651158,0.470461
39,"(protein bar, gadget for tiktok streaming)",(energy drink),0.124443,0.585932,0.106440,0.855332,1.459781,1.0,0.033525,2.862194,0.359732,0.176245,0.650618,0.518496
37,"(gadget for tiktok streaming, pancakes)",(energy drink),0.155252,0.585932,0.132517,0.853556,1.456751,1.0,0.041549,2.827495,0.371165,0.217716,0.646330,0.539860
49,"(protein bar, iphone 10)",(energy drink),0.082777,0.585932,0.070620,0.853139,1.456038,1.0,0.022118,2.819457,0.341471,0.118076,0.645322,0.486832
55,"(phone car charger, pancakes)",(energy drink),0.087231,0.585932,0.074332,0.852128,1.454312,1.0,0.023221,2.800174,0.342244,0.124128,0.642879,0.489494
53,"(pancakes, metroid fusion)",(energy drink),0.065702,0.585932,0.055958,0.851695,1.453574,1.0,0.017461,2.792003,0.333984,0.093940,0.641834,0.473598
23,"(airpods, pancakes)",(energy drink),0.150705,0.585932,0.127691,0.847291,1.446057,1.0,0.039388,2.711480,0.363201,0.209692,0.631198,0.532610
19,"(airpods, energy bar)",(energy drink),0.078786,0.585932,0.066537,0.844523,1.441333,1.0,0.020373,2.663212,0.332385,0.111232,0.624514,0.479040
44,"(protein bar, iMac)",(energy drink),0.067836,0.585932,0.057257,0.844049,1.440525,1.0,0.017510,2.655122,0.328063,0.095986,0.623369,0.470884
30,"(cider, dessert wine)",(white wine),0.074332,0.250186,0.062639,0.842697,3.368286,1.0,0.044042,4.766677,0.759574,0.239192,0.790210,0.546534
58,"(phone car charger, protein bar)",(energy drink),0.066908,0.585932,0.055772,0.833564,1.422631,1.0,0.016569,2.487860,0.318379,0.093410,0.598048,0.464375
24,"(airpods, protein bar)",(energy drink),0.115256,0.585932,0.095861,0.831723,1.419488,1.0,0.028329,2.460636,0.334018,0.158363,0.593601,0.497664
28,"(beer, cider)",(white wine),0.063010,0.250186,0.051875,0.823270,3.290635,1.0,0.036110,4.242700,0.742919,0.198509,0.764301,0.515307
36,"(iphone 10, gadget for tiktok streaming)",(energy drink),0.068578,0.585932,0.056422,0.822733,1.404146,1.0,0.016239,2.335851,0.309015,0.094337,0.571890,0.459514
8,(iPad),(energy drink),0.104677,0.585932,0.085839,0.820035,1.399541,1.0,0.024505,2.300833,0.318857,0.141936,0.565375,0.483268
4,(energy bar),(energy drink),0.222346,0.585932,0.181978,0.818447,1.396831,1.0,0.051699,2.280707,0.365321,0.290562,0.561540,0.564514
13,(pancakes),(energy drink),0.425019,0.585932,0.346325,0.814847,1.390686,1.0,0.097293,2.236359,0.488591,0.521083,0.552845,0.702957
17,(protein bar),(energy drink),0.328415,0.585932,0.265590,0.808703,1.380200,1.0,0.073161,2.164531,0.410175,0.409383,0.538006,0.630991
11,(metroid fusion),(energy drink),0.109317,0.585932,0.088252,0.807301,1.377807,1.0,0.024199,2.148777,0.307863,0.145391,0.534619,0.478959
20,"(airpods, gadget for tiktok streaming)",(energy drink),0.097532,0.585932,0.078508,0.804948,1.373791,1.0,0.021361,2.122857,0.301492,0.129775,0.528937,0.469468
21,"(airpods, iphone 10)",(energy drink),0.065702,0.585932,0.052339,0.796610,1.359561,1.0,0.013842,2.035836,0.283067,0.087334,0.508801,0.442968
16,(pokemon violet),(energy drink),0.067558,0.585932,0.053174,0.787088,1.343310,1.0,0.013590,1.944785,0.274087,0.088576,0.485804,0.438919
15,(pokemon scarlet),(energy drink),0.068022,0.585932,0.053174,0.781719,1.334147,1.0,0.013318,1.896950,0.268737,0.088508,0.472838,0.436235
12,(metroid prime),(energy drink),0.090200,0.585932,0.070063,0.776749,1.325665,1.0,0.017212,1.854721,0.270017,0.115603,0.460835,0.448162
1,(brownies),(energy drink),0.092799,0.585932,0.070156,0.756000,1.290253,1.0,0.015782,1.697001,0.247969,0.115279,0.410725,0.437867
5,(gadget for tiktok streaming),(energy drink),0.297420,0.585932,0.214736,0.721997,1.232220,1.0,0.040469,1.489438,0.268235,0.321166,0.328606,0.544242
0,(airpods),(energy drink),0.276726,0.585932,0.199146,0.719651,1.228217,1.0,0.037004,1.476976,0.256903,0.300140,0.322941,0.529765
6,(half-life 2),(energy drink),0.137899,0.585932,0.099202,0.719381,1.227756,1.0,0.018403,1.475553,0.215179,0.158817,0.322288,0.444344
9,(iphone 10),(energy drink),0.196177,0.585932,0.140683,0.717124,1.223904,1.0,0.025737,1.463780,0.227590,0.219329,0.316837,0.478613
7,(iMac),(energy drink),0.167131,0.585932,0.119339,0.714048,1.218654,1.0,0.021412,1.448033,0.215427,0.188315,0.309408,0.458861
14,(phone car charger),(energy drink),0.165646,0.585932,0.117112,0.707003,1.206630,1.0,0.020055,1.413216,0.205243,0.184584,0.292394,0.453438
2,(cider),(white wine),0.191444,0.250186,0.134744,0.703829,2.813229,1.0,0.086847,2.531697,0.797145,0.439069,0.605008,0.621203
63,"(airpods, protein bar, energy drink)",(pancakes),0.095861,0.425019,0.063567,0.663117,1.560207,1.0,0.022824,1.706770,0.397129,0.139002,0.414098,0.406340
62,"(airpods, gadget for tiktok streaming, energy ...",(pancakes),0.078508,0.425019,0.051132,0.651300,1.532404,1.0,0.017765,1.648930,0.377031,0.113026,0.393546,0.385803
3,(dessert wine),(white wine),0.150705,0.250186,0.097996,0.650246,2.599056,1.0,0.060291,2.143836,0.724419,0.323529,0.533546,0.520969
68,"(protein bar, gadget for tiktok streaming, ene...",(pancakes),0.106440,0.425019,0.069042,0.648649,1.526165,1.0,0.023803,1.636486,0.385831,0.149308,0.388934,0.405547
65,"(protein bar, energy drink, energy bar)",(pancakes),0.090664,0.425019,0.058556,0.645855,1.519592,1.0,0.020022,1.623575,0.376020,0.128096,0.384075,0.391814
42,"(energy drink, iMac)",(pancakes),0.119339,0.425019,0.076745,0.643079,1.513062,1.0,0.026023,1.610950,0.385039,0.164120,0.379248,0.411824

Associations with more than 1 item:

In [24]:
frequent_itemsets_2 = apriori(
    dataset_cluster_5_basket, min_support=0.02, use_colnames=True
    )

rules_2 = association_rules(frequent_itemsets_2,
                                  metric="confidence",
                                  min_threshold=0.2, num_itemsets=100)

rules_2.sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1082,"(white wine, dessert wine)","(champagne, cider)",0.097996,0.050761,0.021158,0.215909,4.253449,1.0,0.016184,1.210624,0.847997,0.165818,0.173980,0.316364
1083,"(champagne, cider)","(white wine, dessert wine)",0.050761,0.097996,0.021158,0.416819,4.253449,1.0,0.016184,1.546697,0.805800,0.165818,0.353461,0.316364
1081,"(white wine, champagne)","(cider, dessert wine)",0.068022,0.074332,0.021158,0.311050,4.184619,1.0,0.016102,1.343594,0.816574,0.174579,0.255727,0.297847
1085,"(cider, dessert wine)","(white wine, champagne)",0.074332,0.068022,0.021158,0.284644,4.184619,1.0,0.016102,1.302818,0.822141,0.174579,0.232433,0.297847
1067,"(beer, cider)","(white wine, dessert wine)",0.063010,0.097996,0.025612,0.406480,4.147945,1.0,0.019438,1.519754,0.809952,0.189171,0.341999,0.333922
1066,"(white wine, dessert wine)","(beer, cider)",0.097996,0.063010,0.025612,0.261364,4.147945,1.0,0.019438,1.268540,0.841367,0.189171,0.211692,0.333922
1084,"(champagne, dessert wine)","(white wine, cider)",0.038512,0.134744,0.021158,0.549398,4.077347,1.0,0.015969,1.920221,0.784973,0.139109,0.479227,0.353211
1069,"(cider, dessert wine)","(white wine, beer)",0.074332,0.084911,0.025612,0.344569,4.058009,1.0,0.019301,1.396164,0.814086,0.191667,0.283752,0.323104
1065,"(white wine, beer)","(cider, dessert wine)",0.084911,0.074332,0.025612,0.301639,4.058009,1.0,0.019301,1.325487,0.823498,0.191667,0.245560,0.323104
1068,"(beer, dessert wine)","(white wine, cider)",0.049740,0.134744,0.025612,0.514925,3.821512,1.0,0.018910,1.783759,0.776970,0.161215,0.439386,0.352504

------

## Cluster 6 - **University Low-Spenders**

In [25]:
te = TransactionEncoder()
te_fit = te.fit(cluster_6_basket['list_of_goods']).transform(cluster_6_basket['list_of_goods'])
dataset_cluster_6_basket = pd.DataFrame(te_fit, columns=te.columns_)

dataset_cluster_6_basket

,airpods,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,beer,black beer,...,vacuum cleaner,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
3,False,False,False,False,True,True,False,True,True,True,...,False,False,False,True,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1726,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1727,False,True,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1728,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1729,True,True,False,False,False,True,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
1730,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False

## Apriori algorithm

In [26]:
frequent_itemsets = apriori(dataset_cluster_6_basket, min_support=0.05, use_colnames=True)
display(frequent_itemsets.sort_values(by='support', ascending=False))

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6, num_itemsets=100)
rules = rules.sort_values(by='confidence', ascending=False)

display(rules.head(50).sort_values(by='confidence', ascending=False))

      support                      itemsets
2    0.787984                        (beer)
37   0.575968                  (white wine)
67   0.471404            (white wine, beer)
31   0.430387                        (salt)
11   0.365685                       (cider)
..        ...                           ...
164  0.050260      (white wine, beer, soup)
91   0.050260                 (gums, cider)
176  0.050260  (white wine, red wine, salt)
85   0.050260         (champagne, red wine)
28   0.050260                       (pasta)

[184 rows x 2 columns]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
59,"(white wine, candy bars)",(beer),0.068746,0.787984,0.064125,0.932773,1.183747,1.0,0.009954,3.153741,0.166683,0.080904,0.682916,0.507076
78,"(ketchup, dessert wine)",(beer),0.057192,0.787984,0.053148,0.929293,1.179330,1.0,0.008082,2.998514,0.161285,0.067104,0.666502,0.498371
46,"(salt, black beer)",(beer),0.067013,0.787984,0.061814,0.922414,1.170600,1.0,0.009009,2.732653,0.156205,0.077932,0.634055,0.500430
116,"(white wine, cake, salt)",(beer),0.076256,0.787984,0.069902,0.916667,1.163306,1.0,0.009813,2.544194,0.151970,0.088000,0.606948,0.502688
53,"(champagne, cake)",(beer),0.056615,0.787984,0.050838,0.897959,1.139566,1.0,0.006226,2.077759,0.129822,0.064047,0.518712,0.481238
69,"(ketchup, cider)",(beer),0.063547,0.787984,0.056615,0.890909,1.130619,1.0,0.006541,1.943482,0.123368,0.071221,0.485459,0.481378
19,(oatmeal),(beer),0.078567,0.787984,0.069902,0.889706,1.129092,1.0,0.007992,1.922280,0.124081,0.087745,0.479784,0.489208
56,"(cake, salt)",(beer),0.119584,0.787984,0.106297,0.888889,1.128055,1.0,0.012067,1.908146,0.128937,0.132660,0.475931,0.511893
92,"(white wine, ketchup)",(beer),0.100520,0.787984,0.088966,0.885057,1.123192,1.0,0.009758,1.844541,0.121938,0.111272,0.457860,0.498980
128,"(white wine, salt, french wine)",(beer),0.059503,0.787984,0.052571,0.883495,1.121210,1.0,0.005683,1.819806,0.114946,0.066134,0.450491,0.475105
91,"(ketchup, salt)",(beer),0.067591,0.787984,0.059503,0.880342,1.117208,1.0,0.006243,1.771849,0.112517,0.074746,0.435618,0.477928
55,"(cake, dessert wine)",(beer),0.075101,0.787984,0.065858,0.876923,1.112869,1.0,0.006679,1.722631,0.109657,0.082609,0.419493,0.480250
45,"(cider, black beer)",(beer),0.064702,0.787984,0.056615,0.875000,1.110429,1.0,0.005630,1.696129,0.106327,0.071118,0.410422,0.473424
120,"(white wine, cider, dessert wine)",(beer),0.083189,0.787984,0.072790,0.875000,1.110429,1.0,0.007239,1.696129,0.108471,0.091172,0.410422,0.483688
83,"(french fries, salt)",(beer),0.086655,0.787984,0.075679,0.873333,1.108314,1.0,0.007396,1.673812,0.107001,0.094722,0.402561,0.484687
70,"(cider, red wine)",(beer),0.072213,0.787984,0.062969,0.872000,1.106622,1.0,0.006067,1.656376,0.103848,0.078986,0.396272,0.475956
21,(pet food),(beer),0.071635,0.787984,0.062392,0.870968,1.105312,1.0,0.005945,1.643125,0.102630,0.078261,0.391404,0.475073
57,"(white wine, cake)",(beer),0.142692,0.787984,0.124206,0.870445,1.104649,1.0,0.011767,1.636500,0.110503,0.154011,0.388940,0.514035
89,"(white wine, gums)",(beer),0.070479,0.787984,0.061236,0.868852,1.102627,1.0,0.005700,1.616623,0.100133,0.076812,0.381427,0.473283
54,"(cider, cake)",(beer),0.092432,0.787984,0.080300,0.868750,1.102497,1.0,0.007465,1.615361,0.102437,0.100361,0.380943,0.485328
67,"(cider, french fries)",(beer),0.064125,0.787984,0.055459,0.864865,1.097567,1.0,0.004930,1.568920,0.094985,0.069616,0.362619,0.467623
71,"(cider, salt)",(beer),0.162334,0.787984,0.139804,0.861210,1.092928,1.0,0.011887,1.527604,0.101505,0.172488,0.345380,0.519315
94,"(white wine, muffins)",(beer),0.061814,0.787984,0.053148,0.859813,1.091156,1.0,0.004440,1.512382,0.089045,0.066715,0.338791,0.463631
63,"(champagne, salt)",(beer),0.102831,0.787984,0.088388,0.859551,1.090823,1.0,0.007359,1.509555,0.092804,0.110151,0.337553,0.485860
101,"(white wine, salt)",(beer),0.262854,0.787984,0.225881,0.859341,1.090556,1.0,0.018756,1.507302,0.112646,0.273810,0.336563,0.572999
79,"(red wine, dessert wine)",(beer),0.061236,0.787984,0.052571,0.858491,1.089477,1.0,0.004318,1.498248,0.087486,0.065990,0.332554,0.462603
66,"(cider, dessert wine)",(beer),0.126516,0.787984,0.108608,0.858447,1.089423,1.0,0.008915,1.497792,0.093972,0.134767,0.332350,0.498139
62,"(champagne, dessert wine)",(beer),0.069324,0.787984,0.059503,0.858333,1.089278,1.0,0.004877,1.496585,0.088066,0.074584,0.331812,0.466923
5,(candy bars),(beer),0.111496,0.787984,0.095321,0.854922,1.084949,1.0,0.007463,1.461397,0.088123,0.118534,0.315723,0.487945
118,"(white wine, champagne, salt)",(beer),0.067591,0.787984,0.057770,0.854701,1.084668,1.0,0.004509,1.459170,0.083717,0.072411,0.314679,0.464007
126,"(white wine, french fries, salt)",(beer),0.059503,0.787984,0.050838,0.854369,1.084247,1.0,0.003950,1.455844,0.082617,0.063814,0.313113,0.459443
47,"(white wine, black beer)",(beer),0.094165,0.787984,0.080300,0.852761,1.082206,1.0,0.006100,1.439943,0.083858,0.100144,0.305528,0.477333
81,"(white wine, dessert wine)",(beer),0.195841,0.787984,0.166956,0.852507,1.081884,1.0,0.012636,1.437470,0.094119,0.204385,0.304333,0.532192
77,"(french wine, dessert wine)",(beer),0.066436,0.787984,0.056615,0.852174,1.081461,1.0,0.004265,1.434227,0.080685,0.070963,0.302760,0.462011
98,"(red wine, salt)",(beer),0.081456,0.787984,0.069324,0.851064,1.080052,1.0,0.005138,1.423537,0.080692,0.086643,0.297524,0.469520
96,"(napkins, white wine)",(beer),0.065858,0.787984,0.056037,0.850877,1.079816,1.0,0.004142,1.421756,0.079127,0.070239,0.296644,0.460996
122,"(white wine, cider, salt)",(beer),0.104564,0.787984,0.088966,0.850829,1.079754,1.0,0.006571,1.421294,0.082488,0.110712,0.296416,0.481866
84,"(white wine, french fries)",(beer),0.118429,0.787984,0.100520,0.848780,1.077155,1.0,0.007200,1.402042,0.081251,0.124731,0.286755,0.488173
15,(ketchup),(beer),0.156557,0.787984,0.132871,0.848708,1.077063,1.0,0.009507,1.401375,0.084830,0.163701,0.286415,0.508665
99,"(white wine, red wine)",(beer),0.114385,0.787984,0.097054,0.848485,1.076780,1.0,0.006920,1.399307,0.080514,0.120516,0.285360,0.485826
87,"(white wine, french wine)",(beer),0.121895,0.787984,0.103408,0.848341,1.076597,1.0,0.007357,1.397982,0.081024,0.128223,0.284683,0.489786
49,"(bramble, cider)",(beer),0.060659,0.787984,0.051415,0.847619,1.075681,1.0,0.003617,1.391356,0.074899,0.064493,0.281277,0.456434
124,"(white wine, salt, dessert wine)",(beer),0.094743,0.787984,0.080300,0.847561,1.075607,1.0,0.005645,1.390826,0.077649,0.100072,0.281003,0.474734
80,"(salt, dessert wine)",(beer),0.142692,0.787984,0.120739,0.846154,1.073821,1.0,0.008300,1.378105,0.080189,0.149073,0.274366,0.499690
103,"(white wine, soup)",(beer),0.059503,0.787984,0.050260,0.844660,1.071926,1.0,0.003372,1.364854,0.071345,0.063043,0.267321,0.454222
2,(black beer),(beer),0.148469,0.787984,0.124783,0.840467,1.066604,1.0,0.007792,1.328979,0.073333,0.153737,0.247543,0.499412
51,"(bramble, white wine)",(beer),0.083189,0.787984,0.069902,0.840278,1.066364,1.0,0.004350,1.327406,0.067881,0.087239,0.246651,0.464494
11,(french fries),(beer),0.187175,0.787984,0.157135,0.839506,1.065385,1.0,0.009644,1.321024,0.075505,0.192090,0.243011,0.519460
23,(salt),(beer),0.430387,0.787984,0.359908,0.836242,1.061242,1.0,0.020770,1.294689,0.101311,0.419246,0.227614,0.646493
86,"(french wine, salt)",(beer),0.094165,0.787984,0.078567,0.834356,1.058849,1.0,0.004367,1.279950,0.061356,0.097771,0.218719,0.467031

Associations with more than 1 item:

In [27]:
frequent_itemsets_2 = apriori(
    dataset_cluster_6_basket, min_support=0.02, use_colnames=True
    )

rules_2 = association_rules(frequent_itemsets_2,
                                  metric="confidence",
                                  min_threshold=0.2, num_itemsets=100)

rules_2.sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1773,"(beer, muffins)","(salt, dessert wine)",0.079723,0.142692,0.020220,0.253623,1.777416,1.0,0.008844,1.148626,0.475276,0.100000,0.129395,0.197662
1326,"(bramble, white wine)","(beer, red wine)",0.083189,0.153668,0.021375,0.256944,1.672071,1.0,0.008591,1.138988,0.438410,0.099196,0.122028,0.198021
1776,(muffins),"(beer, salt, dessert wine)",0.100520,0.120739,0.020220,0.201149,1.665979,1.0,0.008083,1.100657,0.444426,0.100575,0.091452,0.184307
2065,"(ketchup, salt)","(white wine, beer, cider)",0.067591,0.181398,0.020220,0.299145,1.649110,1.0,0.007959,1.168005,0.422146,0.088384,0.143839,0.205305
1322,"(bramble, beer, white wine)",(red wine),0.069902,0.186020,0.021375,0.305785,1.643832,1.0,0.008372,1.172519,0.421101,0.091133,0.147136,0.210346
1760,"(ketchup, salt)","(beer, dessert wine)",0.067591,0.250722,0.027730,0.410256,1.636299,1.0,0.010783,1.270515,0.417054,0.095427,0.212917,0.260428
1771,"(beer, dessert wine, muffins)",(salt),0.028885,0.430387,0.020220,0.700000,1.626443,1.0,0.007788,1.898710,0.396618,0.046053,0.473327,0.373490
1324,"(white wine, beer, red wine)",(bramble),0.097054,0.135760,0.021375,0.220238,1.622264,1.0,0.008199,1.108339,0.424807,0.101093,0.097749,0.188842
1775,"(dessert wine, muffins)","(beer, salt)",0.034662,0.359908,0.020220,0.583333,1.620787,1.0,0.007744,1.536222,0.396768,0.054012,0.349052,0.319757
1820,"(french fries, salt)","(french wine, beer)",0.086655,0.161179,0.022530,0.260000,1.613118,1.0,0.008563,1.133543,0.416144,0.100000,0.117810,0.199892

------

## Cluster 7 - **Hygiene Obsessed**

In [28]:
te = TransactionEncoder()
te_fit = te.fit(cluster_7_basket['list_of_goods']).transform(cluster_7_basket['list_of_goods'])
dataset_cluster_7_basket = pd.DataFrame(te_fit, columns=te.columns_)

dataset_cluster_7_basket

,airpods,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,beer,black beer,...,vacuum cleaner,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,True,False,False,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15123,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
15124,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
15125,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
15126,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
15127,False,False,False,False,False,False,False,True,False,False,...,False,False,True,False,False,False,False,False,False,False

## Apriori algorithm

In [29]:
frequent_itemsets = apriori(dataset_cluster_7_basket, min_support=0.05, use_colnames=True)
display(frequent_itemsets.sort_values(by='support', ascending=False))

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6, num_itemsets=100)
rules = rules.sort_values(by='confidence', ascending=False)

display(rules.head(50).sort_values(by='confidence', ascending=False))

      support                                  itemsets
26   0.784836                                     (oil)
2    0.553940                          (barbecue sauce)
56   0.465693                     (barbecue sauce, oil)
9    0.435484                                 (cologne)
82   0.366142                            (cologne, oil)
..        ...                                       ...
152  0.050436              (toilet paper, chicken, oil)
130  0.050370  (mineral water, barbecue sauce, cologne)
154  0.050304                 (deodorant, cologne, ham)
120  0.050238         (barbecue sauce, candy bars, oil)
117  0.050106         (cologne, antioxydant juice, oil)

[175 rows x 2 columns]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
109,"(barbecue sauce, cologne, chicken)",(oil),0.091552,0.784836,0.081703,0.892419,1.137077,1.0,0.009849,2.000014,0.132701,0.102812,0.500003,0.498260
119,"(ham, barbecue sauce, cologne)",(oil),0.080447,0.784836,0.071721,0.891537,1.135953,1.0,0.008584,1.983746,0.130152,0.090379,0.495903,0.491460
113,"(barbecue sauce, cologne, cooking oil)",(oil),0.063062,0.784836,0.055857,0.885744,1.128572,1.0,0.006363,1.883178,0.121593,0.070522,0.468983,0.478457
117,"(barbecue sauce, cologne, fresh tuna)",(oil),0.068020,0.784836,0.060219,0.885326,1.128039,1.0,0.006835,1.876302,0.121790,0.075974,0.467037,0.481027
115,"(deodorant, barbecue sauce, cologne)",(oil),0.108342,0.784836,0.095650,0.882855,1.124891,1.0,0.010620,1.836738,0.124516,0.119934,0.455557,0.502364
82,"(barbecue sauce, samsung galaxy 10)",(oil),0.069672,0.784836,0.061475,0.882353,1.124251,1.0,0.006794,1.828893,0.118796,0.077519,0.453221,0.480341
111,"(deodorant, barbecue sauce, chicken)",(oil),0.071060,0.784836,0.062599,0.880930,1.122439,1.0,0.006828,1.807041,0.117427,0.078910,0.446609,0.480346
121,"(deodorant, barbecue sauce, ham)",(oil),0.064781,0.784836,0.057047,0.880612,1.122033,1.0,0.006204,1.802228,0.116295,0.071977,0.445131,0.476649
100,"(mineral water, cologne)",(oil),0.079389,0.784836,0.069870,0.880100,1.121381,1.0,0.007563,1.794527,0.117576,0.087959,0.442750,0.484563
108,"(ham, fresh tuna)",(oil),0.061740,0.784836,0.054270,0.879015,1.119998,1.0,0.005815,1.778435,0.114192,0.068497,0.437708,0.474082
91,"(cooking oil, chicken)",(oil),0.066830,0.784836,0.058699,0.878338,1.119136,1.0,0.006249,1.768543,0.114077,0.074025,0.434563,0.476565
93,"(fresh tuna, chicken)",(oil),0.070003,0.784836,0.061475,0.878187,1.118943,1.0,0.006535,1.766346,0.114301,0.077487,0.433859,0.478258
65,"(barbecue sauce, cologne)",(oil),0.269104,0.784836,0.236185,0.877671,1.118286,1.0,0.024982,1.758900,0.144719,0.288821,0.431463,0.589303
46,"(cologne, antioxydant juice)",(oil),0.057113,0.784836,0.050106,0.877315,1.117832,1.0,0.005282,1.753789,0.111796,0.063277,0.429806,0.470579
49,"(barbecue sauce, cake)",(oil),0.086727,0.784836,0.076084,0.877287,1.117796,1.0,0.008018,1.753386,0.115390,0.095646,0.429675,0.487115
123,"(deodorant, cologne, chicken)",(oil),0.058369,0.784836,0.051163,0.876557,1.116867,1.0,0.005354,1.743025,0.111124,0.064597,0.426285,0.470874
47,"(barbecue sauce, black tea)",(oil),0.078067,0.784836,0.068350,0.875529,1.115557,1.0,0.007080,1.728630,0.112358,0.086023,0.421507,0.481309
76,"(ham, barbecue sauce)",(oil),0.157985,0.784836,0.138154,0.874477,1.114216,1.0,0.014162,1.714139,0.121741,0.171691,0.416617,0.525253
68,"(barbecue sauce, cooking oil)",(oil),0.124736,0.784836,0.109003,0.873874,1.113448,1.0,0.011106,1.705943,0.116409,0.136157,0.413814,0.506380
106,"(mineral water, deodorant)",(oil),0.061343,0.784836,0.053543,0.872845,1.112136,1.0,0.005399,1.692137,0.107419,0.067551,0.409031,0.470533
78,"(mineral water, barbecue sauce)",(oil),0.101996,0.784836,0.088974,0.872327,1.111476,1.0,0.008924,1.685269,0.111687,0.111516,0.406623,0.492847
99,"(ham, cologne)",(oil),0.122158,0.784836,0.106557,0.872294,1.111435,1.0,0.010684,1.684843,0.114215,0.133124,0.406473,0.504032
86,"(toilet paper, barbecue sauce)",(oil),0.108012,0.784836,0.093998,0.870257,1.108839,1.0,0.009226,1.658386,0.110042,0.117667,0.397004,0.495012
98,"(cologne, fresh tuna)",(oil),0.105368,0.784836,0.091684,0.870138,1.108688,1.0,0.008988,1.656866,0.109579,0.114818,0.396451,0.493479
96,"(cooking oil, cologne)",(oil),0.097171,0.784836,0.084545,0.870068,1.108598,1.0,0.008282,1.655974,0.108503,0.106018,0.396126,0.488896
89,"(cologne, cake)",(oil),0.069804,0.784836,0.060682,0.869318,1.107643,1.0,0.005897,1.646472,0.104475,0.076430,0.392641,0.473318
104,"(deodorant, fresh tuna)",(oil),0.081240,0.784836,0.070531,0.868186,1.106200,1.0,0.006771,1.632324,0.104493,0.088658,0.387376,0.479027
90,"(cologne, chicken)",(oil),0.140865,0.784836,0.122290,0.868137,1.106138,1.0,0.011734,1.631724,0.111686,0.152213,0.387151,0.511976
105,"(deodorant, ham)",(oil),0.098559,0.784836,0.085537,0.867874,1.105803,1.0,0.008184,1.628474,0.106141,0.107208,0.385928,0.488430
58,"(barbecue sauce, chicken)",(oil),0.177287,0.784836,0.153622,0.866518,1.104075,1.0,0.014481,1.611926,0.114577,0.190009,0.379624,0.531128
72,"(deodorant, barbecue sauce)",(oil),0.210074,0.784836,0.181980,0.866268,1.103757,1.0,0.017107,1.608920,0.119003,0.223858,0.378465,0.549069
97,"(deodorant, cologne)",(oil),0.166777,0.784836,0.144434,0.866033,1.103457,1.0,0.013542,1.606091,0.112523,0.178937,0.377370,0.525032
74,"(barbecue sauce, fresh tuna)",(oil),0.133792,0.784836,0.115812,0.865613,1.102922,1.0,0.010807,1.601073,0.107731,0.144257,0.375419,0.506587
94,"(ham, chicken)",(oil),0.077604,0.784836,0.066962,0.862862,1.099417,1.0,0.006055,1.568959,0.098035,0.084178,0.362635,0.474091
92,"(deodorant, chicken)",(oil),0.112374,0.784836,0.096906,0.862353,1.098768,1.0,0.008711,1.563157,0.101270,0.121087,0.360269,0.492913
44,"(barbecue sauce, antioxydant juice)",(oil),0.073704,0.784836,0.063458,0.860987,1.097027,1.0,0.005613,1.547792,0.095483,0.079814,0.353918,0.470921
103,"(deodorant, cooking oil)",(oil),0.079720,0.784836,0.068548,0.859867,1.095601,1.0,0.005981,1.535430,0.094818,0.086115,0.348717,0.473604
102,"(toilet paper, cologne)",(oil),0.082364,0.784836,0.070796,0.859551,1.095198,1.0,0.006154,1.531967,0.094725,0.088894,0.347245,0.474878
95,"(toilet paper, chicken)",(oil),0.058765,0.784836,0.050436,0.858268,1.093563,1.0,0.004315,1.518101,0.090900,0.063589,0.341282,0.461266
88,"(black tea, cologne)",(oil),0.059492,0.784836,0.051031,0.857778,1.092939,1.0,0.004339,1.512871,0.090415,0.064328,0.339005,0.461400
53,"(barbecue sauce, catfish)",(oil),0.061608,0.784836,0.052816,0.857296,1.092325,1.0,0.004464,1.507765,0.090071,0.066550,0.336767,0.462296
107,"(deodorant, toilet paper)",(oil),0.067028,0.784836,0.057377,0.856016,1.090694,1.0,0.004771,1.494358,0.089126,0.072219,0.330816,0.464561
84,"(barbecue sauce, shrimp)",(oil),0.069540,0.784836,0.059426,0.854563,1.088842,1.0,0.004849,1.479428,0.087691,0.074755,0.324063,0.465140
80,"(barbecue sauce, mint green tea)",(oil),0.088577,0.784836,0.075687,0.854478,1.088734,1.0,0.006169,1.478562,0.089423,0.094879,0.323667,0.475457
51,"(barbecue sauce, candy bars)",(oil),0.058964,0.784836,0.050238,0.852018,1.085600,1.0,0.003961,1.453987,0.083791,0.063307,0.312236,0.458014
101,"(cologne, mint green tea)",(oil),0.072316,0.784836,0.061409,0.849177,1.081981,1.0,0.004653,1.426602,0.081675,0.077172,0.299034,0.463711
27,(frozen vegetables),(oil),0.090494,0.784836,0.076481,0.845142,1.076839,1.0,0.005457,1.389431,0.078456,0.095739,0.280281,0.471295
33,(mineral water),(oil),0.164992,0.784836,0.139146,0.843349,1.074555,1.0,0.009654,1.373527,0.083091,0.171641,0.271947,0.510321
30,(ham),(oil),0.251256,0.784836,0.211859,0.843199,1.074363,1.0,0.014664,1.372212,0.092443,0.257037,0.271249,0.556570
40,(soup),(oil),0.075423,0.784836,0.063525,0.842244,1.073146,1.0,0.004330,1.363900,0.073721,0.079731,0.266809,0.461592

Associations with more than 1 item:

In [30]:
frequent_itemsets_2 = apriori(
    dataset_cluster_7_basket, min_support=0.02, use_colnames=True
    )

rules_2 = association_rules(frequent_itemsets_2,
                                  metric="confidence",
                                  min_threshold=0.2, num_itemsets=100)

rules_2.sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1850,"(cooking oil, cologne)","(barbecue sauce, chicken, oil)",0.097171,0.153622,0.020624,0.212245,1.381601,1.0,0.005696,1.074417,0.305929,0.089604,0.069263,0.173248
1844,"(cooking oil, cologne, oil)","(barbecue sauce, chicken)",0.084545,0.177287,0.020624,0.243941,1.375963,1.0,0.005635,1.088159,0.298471,0.085503,0.081017,0.180136
1857,"(deodorant, cologne, oil)","(barbecue sauce, chicken)",0.144434,0.177287,0.034638,0.239817,1.352703,1.0,0.009031,1.082256,0.304757,0.120654,0.076004,0.217597
1865,"(deodorant, cologne)","(barbecue sauce, chicken, oil)",0.166777,0.153622,0.034638,0.207689,1.351946,1.0,0.009017,1.068239,0.312432,0.121212,0.063880,0.216581
1864,"(barbecue sauce, chicken, oil)","(deodorant, cologne)",0.153622,0.166777,0.034638,0.225473,1.351946,1.0,0.009017,1.075784,0.307576,0.121212,0.070445,0.216581
1866,"(cologne, chicken)","(deodorant, barbecue sauce, oil)",0.140865,0.181980,0.034638,0.245894,1.351211,1.0,0.009003,1.084754,0.302540,0.120183,0.078132,0.218116
1845,"(barbecue sauce, cooking oil, cologne)","(chicken, oil)",0.063062,0.242200,0.020624,0.327044,1.350306,1.0,0.005350,1.126077,0.276888,0.072457,0.111961,0.206098
1860,"(cologne, chicken, oil)","(deodorant, barbecue sauce)",0.122290,0.210074,0.034638,0.283243,1.348302,1.0,0.008948,1.102084,0.294319,0.116341,0.092628,0.224063
1382,"(shrimp, oil)","(barbecue sauce, chicken)",0.092081,0.177287,0.021946,0.238335,1.344342,1.0,0.005621,1.080150,0.282119,0.088699,0.074203,0.181061
1287,"(cooking oil, cologne)","(barbecue sauce, chicken)",0.097171,0.177287,0.023070,0.237415,1.339155,1.0,0.005843,1.078847,0.280519,0.091770,0.073085,0.183771

------

## Cluster 8 - **Loyal Average Spenders**

In [31]:
te = TransactionEncoder()
te_fit = te.fit(cluster_8_basket['list_of_goods']).transform(cluster_8_basket['list_of_goods'])
dataset_cluster_8_basket = pd.DataFrame(te_fit, columns=te.columns_)

dataset_cluster_8_basket

,airpods,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,beer,black beer,...,vacuum cleaner,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17142,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
17143,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
17144,False,False,False,True,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17145,False,False,True,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17146,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

## Apriori algorithm

In [32]:
frequent_itemsets = apriori(dataset_cluster_8_basket, min_support=0.05, use_colnames=True)
display(frequent_itemsets.sort_values(by='support', ascending=False))

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6, num_itemsets=100)
rules = rules.sort_values(by='confidence', ascending=False)

display(rules.head(50).sort_values(by='confidence', ascending=False))

      support                                itemsets
1    0.771447                           (babies food)
27   0.551583                       (ratchet & clank)
60   0.456056          (babies food, ratchet & clank)
16   0.425672                             (minecraft)
51   0.354173                (babies food, minecraft)
..        ...                                     ...
146  0.050621  (pokemon sword, babies food, pet food)
69   0.050504              (babies food, yogurt cake)
126  0.050330        (milk, cooking oil, babies food)
70   0.050271                (bacon, ratchet & clank)
49   0.050038                  (ketchup, babies food)

[175 rows x 2 columns]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
113,"(cooking oil, pet food, ratchet & clank)",(babies food),0.071208,0.771447,0.063568,0.892711,1.157190,1.0,0.008635,2.130254,0.146252,0.081593,0.530573,0.487556
111,"(cooking oil, ratchet & clank, minecraft)",(babies food),0.103517,0.771447,0.091678,0.885634,1.148017,1.0,0.011820,1.998432,0.143820,0.117043,0.499608,0.502236
108,"(burgers, ratchet & clank, minecraft)",(babies food),0.065026,0.771447,0.057386,0.882511,1.143969,1.0,0.007222,1.945318,0.134603,0.073658,0.485945,0.478449
114,"(cooking oil, ratchet & clank 2, ratchet & clank)",(babies food),0.059777,0.771447,0.052721,0.881951,1.143243,1.0,0.006606,1.936090,0.133261,0.067720,0.483495,0.475146
119,"(pet food, ratchet & clank, minecraft)",(babies food),0.087712,0.771447,0.077215,0.880319,1.141127,1.0,0.009549,1.909688,0.135564,0.098747,0.476354,0.490205
44,"(cooking oil, burgers)",(babies food),0.083746,0.771447,0.073599,0.878830,1.139197,1.0,0.008993,1.886220,0.133357,0.094165,0.469839,0.487117
54,"(cooking oil, pet food)",(babies food),0.112323,0.771447,0.098676,0.878505,1.138775,1.0,0.012025,1.881168,0.137284,0.125687,0.468415,0.503208
120,"(ratchet & clank 2, ratchet & clank, minecraft)",(babies food),0.074474,0.771447,0.065318,0.877056,1.136897,1.0,0.007865,1.858996,0.130102,0.083676,0.462075,0.480862
49,"(ratchet & clank 2, burgers)",(babies food),0.059719,0.771447,0.052312,0.875977,1.135498,1.0,0.006242,1.842822,0.126908,0.067166,0.457354,0.471894
71,"(pokemon sword, minecraft)",(babies food),0.083455,0.771447,0.072957,0.874214,1.133213,1.0,0.008576,1.816997,0.128257,0.093303,0.449641,0.484393
46,"(pet food, burgers)",(babies food),0.070975,0.771447,0.061993,0.873459,1.132235,1.0,0.007240,1.806163,0.125714,0.079435,0.446340,0.476910
55,"(pokemon sword, cooking oil)",(babies food),0.068992,0.771447,0.060244,0.873204,1.131904,1.0,0.007020,1.802522,0.125168,0.077216,0.445222,0.475648
81,"(ratchet & clank 2, pet food)",(babies food),0.081880,0.771447,0.071383,0.871795,1.130078,1.0,0.008217,1.782714,0.125370,0.091289,0.439058,0.482163
75,"(ratchet & clank 3, minecraft)",(babies food),0.063685,0.771447,0.055462,0.870879,1.128891,1.0,0.006332,1.770071,0.121940,0.071135,0.435051,0.471386
52,"(milk, cooking oil)",(babies food),0.057853,0.771447,0.050330,0.869960,1.127699,1.0,0.005699,1.757556,0.120192,0.064610,0.431028,0.467600
80,"(pet food, ratchet & clank)",(babies food),0.176649,0.771447,0.153671,0.869924,1.127653,1.0,0.017396,1.757074,0.137489,0.193437,0.430872,0.534561
70,"(pokemon shield, minecraft)",(babies food),0.061468,0.771447,0.053420,0.869070,1.126546,1.0,0.006001,1.745616,0.119688,0.068532,0.427136,0.469159
78,"(pokemon sword, pet food)",(babies food),0.058261,0.771447,0.050621,0.868869,1.126285,1.0,0.005676,1.742935,0.119062,0.064975,0.426255,0.467244
117,"(escalope, ratchet & clank, minecraft)",(babies food),0.059602,0.771447,0.051729,0.867906,1.125037,1.0,0.005749,1.730232,0.118184,0.066377,0.422043,0.467480
60,"(pet food, escalope)",(babies food),0.062635,0.771447,0.054295,0.866853,1.123671,1.0,0.005976,1.716546,0.117414,0.069628,0.417435,0.468617
58,"(cooking oil, ratchet & clank 2)",(babies food),0.094944,0.771447,0.082288,0.866708,1.123483,1.0,0.009044,1.714675,0.121441,0.104946,0.416799,0.486688
88,"(ratchet & clank 2, ratchet & clank)",(babies food),0.151338,0.771447,0.131160,0.866667,1.123430,1.0,0.014410,1.714148,0.129461,0.165684,0.416620,0.518342
53,"(cooking oil, minecraft)",(babies food),0.164227,0.771447,0.142241,0.866122,1.122724,1.0,0.015548,1.707176,0.130788,0.179272,0.414237,0.525252
85,"(pokemon sword, ratchet & clank)",(babies food),0.109698,0.771447,0.094944,0.865497,1.121914,1.0,0.010317,1.699243,0.122055,0.120763,0.411503,0.494285
95,"(tooth brush, ratchet & clank)",(babies food),0.065842,0.771447,0.056978,0.865368,1.121746,1.0,0.006184,1.697608,0.116182,0.073019,0.410936,0.469613
83,"(ratchet & clank, pokemon shield)",(babies food),0.078789,0.771447,0.068175,0.865285,1.121639,1.0,0.007393,1.696567,0.117723,0.087174,0.410574,0.476829
66,"(milk, minecraft)",(babies food),0.069517,0.771447,0.060127,0.864933,1.121183,1.0,0.006499,1.692145,0.116160,0.077004,0.409034,0.471437
69,"(pet food, minecraft)",(babies food),0.137633,0.771447,0.118971,0.864407,1.120501,1.0,0.012794,1.685579,0.124705,0.150576,0.406732,0.509313
57,"(cooking oil, ratchet & clank)",(babies food),0.211116,0.771447,0.182306,0.863536,1.119372,1.0,0.019441,1.674822,0.135181,0.227809,0.402922,0.549926
68,"(milk, ratchet & clank)",(babies food),0.088820,0.771447,0.076690,0.863427,1.119231,1.0,0.008170,1.673492,0.116914,0.097871,0.402447,0.481419
47,"(burgers, ratchet & clank)",(babies food),0.134134,0.771447,0.115764,0.863043,1.118733,1.0,0.012286,1.668800,0.122573,0.146570,0.400767,0.506552
73,"(ratchet & clank, minecraft)",(babies food),0.256896,0.771447,0.221030,0.860386,1.115289,1.0,0.022848,1.637035,0.139107,0.273785,0.389139,0.573450
45,"(burgers, minecraft)",(babies food),0.104800,0.771447,0.090045,0.859210,1.113764,1.0,0.009198,1.623359,0.114102,0.114532,0.383993,0.487966
59,"(escalope, minecraft)",(babies food),0.095993,0.771447,0.082463,0.859052,1.113560,1.0,0.008410,1.621545,0.112808,0.105052,0.383304,0.482973
74,"(ratchet & clank 2, minecraft)",(babies food),0.117863,0.771447,0.101126,0.857991,1.112184,1.0,0.010200,1.609428,0.114346,0.128302,0.378661,0.494538
91,"(ratchet & clank 3, ratchet & clank)",(babies food),0.082463,0.771447,0.070741,0.857850,1.112001,1.0,0.007125,1.607831,0.109773,0.090327,0.378044,0.474775
50,"(cooking oil, escalope)",(babies food),0.079081,0.771447,0.067592,0.854720,1.107944,1.0,0.006585,1.573188,0.105793,0.086331,0.364348,0.471168
64,"(fresh bread, ratchet & clank)",(babies food),0.096460,0.771447,0.082347,0.853688,1.106606,1.0,0.007933,1.562094,0.106621,0.104826,0.359834,0.480216
77,"(ratchet & clank, muffins)",(babies food),0.061410,0.771447,0.052371,0.852802,1.105457,1.0,0.004996,1.552687,0.101639,0.067100,0.355955,0.460344
63,"(fresh bread, minecraft)",(babies food),0.074824,0.771447,0.063743,0.851910,1.104301,1.0,0.006021,1.543335,0.102088,0.081458,0.352052,0.467269
62,"(escalope, ratchet & clank)",(babies food),0.118913,0.771447,0.101184,0.850907,1.103002,1.0,0.009449,1.532960,0.105986,0.128215,0.347667,0.491034
51,"(cooking oil, fresh bread)",(babies food),0.062577,0.771447,0.053245,0.850885,1.102973,1.0,0.004971,1.532734,0.099592,0.068195,0.347571,0.459953
97,"(turkey, ratchet & clank)",(babies food),0.064618,0.771447,0.054878,0.849278,1.100890,1.0,0.005029,1.516388,0.097975,0.070250,0.340538,0.460207
18,(pokemon sword),(babies food),0.177524,0.771447,0.150055,0.845269,1.095694,1.0,0.013105,1.477103,0.106187,0.187824,0.322999,0.519891
5,(eggs),(babies food),0.091153,0.771447,0.076981,0.844530,1.094735,1.0,0.006662,1.470076,0.095216,0.097988,0.319763,0.472159
15,(pet food),(babies food),0.291538,0.771447,0.245524,0.842168,1.091674,1.0,0.020618,1.448082,0.118532,0.300350,0.309432,0.580216
87,"(ratchet & clank, pokemon violet)",(babies food),0.071674,0.771447,0.060360,0.842148,1.091648,1.0,0.005067,1.447896,0.090435,0.077112,0.309343,0.460196
17,(pokemon shield),(babies food),0.128827,0.771447,0.108357,0.841105,1.090295,1.0,0.008974,1.438387,0.095064,0.136829,0.304777,0.490782
27,(tooth brush),(babies food),0.105966,0.771447,0.089112,0.840947,1.090090,1.0,0.007365,1.436958,0.092440,0.113043,0.304086,0.478230
21,(ratchet & clank 2),(babies food),0.249431,0.771447,0.209483,0.839841,1.088657,1.0,0.017060,1.427039,0.108500,0.258176,0.299248,0.555693

Associations with more than 1 item:

In [33]:
frequent_itemsets_2 = apriori(
    dataset_cluster_8_basket, min_support=0.02, use_colnames=True
    )

rules_2 = association_rules(frequent_itemsets_2,
                                  metric="confidence",
                                  min_threshold=0.2, num_itemsets=100)

rules_2.sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1844,"(ratchet & clank 2, babies food, minecraft)","(pet food, ratchet & clank)",0.101126,0.176649,0.024727,0.244521,1.384222,1.0,0.006864,1.089840,0.308800,0.097718,0.082434,0.192251
1840,"(babies food, pet food, minecraft)","(ratchet & clank 2, ratchet & clank)",0.118971,0.151338,0.024727,0.207843,1.373367,1.0,0.006722,1.071330,0.308574,0.100689,0.066581,0.185617
1845,"(ratchet & clank 2, pet food)","(babies food, ratchet & clank, minecraft)",0.081880,0.221030,0.024727,0.301994,1.366305,1.0,0.006629,1.115994,0.292009,0.088889,0.103938,0.206934
1846,"(ratchet & clank 2, minecraft)","(babies food, pet food, ratchet & clank)",0.117863,0.153671,0.024727,0.209797,1.365234,1.0,0.006615,1.071027,0.303269,0.100189,0.066317,0.185354
1762,"(ratchet & clank 2, minecraft)","(pet food, ratchet & clank)",0.117863,0.176649,0.028227,0.239485,1.355714,1.0,0.007406,1.082624,0.297438,0.106001,0.076318,0.199637
1763,"(pet food, minecraft)","(ratchet & clank 2, ratchet & clank)",0.137633,0.151338,0.028227,0.205085,1.355140,1.0,0.007397,1.067613,0.303895,0.108253,0.063331,0.195799
1839,"(ratchet & clank 2, pet food, ratchet & clank)","(babies food, minecraft)",0.051554,0.354173,0.024727,0.479638,1.354249,1.0,0.006468,1.241112,0.275802,0.064901,0.194271,0.274728
1843,"(ratchet & clank 2, ratchet & clank, minecraft)","(babies food, pet food)",0.074474,0.245524,0.024727,0.332028,1.352325,1.0,0.006442,1.129503,0.281497,0.083745,0.114655,0.216370
1842,"(ratchet & clank 2, babies food, pet food)","(ratchet & clank, minecraft)",0.071383,0.256896,0.024727,0.346405,1.348425,1.0,0.006389,1.136949,0.278257,0.081460,0.120453,0.221330
1838,"(pet food, ratchet & clank, minecraft)","(ratchet & clank 2, babies food)",0.087712,0.209483,0.024727,0.281915,1.345767,1.0,0.006353,1.100869,0.281632,0.090753,0.091626,0.199977

------

## Cluster 9 - **Big Family**

In [34]:
te = TransactionEncoder()
te_fit = te.fit(cluster_9_basket['list_of_goods']).transform(cluster_9_basket['list_of_goods'])
dataset_cluster_9_basket = pd.DataFrame(te_fit, columns=te.columns_)

dataset_cluster_9_basket

,airpods,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,beer,black beer,...,vacuum cleaner,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3917,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3918,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3919,False,False,False,False,False,False,False,False,True,True,...,False,False,True,True,False,False,False,False,False,False
3920,True,False,False,False,False,True,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
3921,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False

## Apriori algorithm

In [35]:
frequent_itemsets = apriori(dataset_cluster_9_basket, min_support=0.05, use_colnames=True)
display(frequent_itemsets.sort_values(by='support', ascending=False))

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6, num_itemsets=100)
rules = rules.sort_values(by='confidence', ascending=False)

display(rules.head(50).sort_values(by='confidence', ascending=False))

      support                                       itemsets
41   0.557114                                   (white wine)
11   0.393677                                        (cider)
10   0.369199                                    (champagne)
81   0.322794                            (white wine, cider)
14   0.310811                                 (dessert wine)
..        ...                                            ...
126  0.050739  (white wine, samsung galaxy 10, dessert wine)
39   0.050484                                        (trout)
118  0.050484             (french wine, cider, dessert wine)
68   0.050229       (gadget for tiktok streaming, champagne)
79   0.050229                            (cider, ring light)

[131 rows x 2 columns]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
53,"(beer, cider, champagne)",(white wine),0.058134,0.557114,0.054309,0.934211,1.676876,1.0,0.021922,6.731871,0.428567,0.096818,0.851453,0.515847
56,"(beer, cider, dessert wine)",(white wine),0.078531,0.557114,0.070372,0.896104,1.608476,1.0,0.026621,4.262780,0.410533,0.124493,0.765411,0.511210
60,"(champagne, cider, dessert wine)",(white wine),0.063488,0.557114,0.056604,0.891566,1.600331,1.0,0.021234,4.084396,0.400560,0.100362,0.755166,0.496584
21,"(beer, cider)",(white wine),0.154258,0.557114,0.136665,0.885950,1.590251,1.0,0.050726,3.883278,0.438867,0.237799,0.742486,0.565630
34,"(bramble, dessert wine)",(white wine),0.092555,0.557114,0.081846,0.884298,1.587284,1.0,0.030282,3.827803,0.407730,0.144140,0.738754,0.515604
37,"(champagne, cider)",(white wine),0.129016,0.557114,0.113463,0.879447,1.578577,1.0,0.041586,3.673778,0.420809,0.198130,0.727801,0.541554
16,"(bramble, beer)",(white wine),0.073687,0.557114,0.064763,0.878893,1.577582,1.0,0.023711,3.656975,0.395243,0.114414,0.726550,0.497570
58,"(bramble, cider, dessert wine)",(white wine),0.060683,0.557114,0.053289,0.878151,1.576251,1.0,0.019482,3.634722,0.389201,0.094399,0.724876,0.486902
45,"(gadget for tiktok streaming, cider)",(white wine),0.065273,0.557114,0.057114,0.875000,1.570595,1.0,0.020749,3.543090,0.388668,0.101037,0.717761,0.488759
50,"(red wine, dessert wine)",(white wine),0.067058,0.557114,0.058644,0.874525,1.569742,1.0,0.021285,3.529669,0.389041,0.103697,0.716687,0.489894
22,"(beer, dessert wine)",(white wine),0.126466,0.557114,0.110403,0.872984,1.566976,1.0,0.039947,3.486851,0.414212,0.192616,0.713208,0.535577
33,"(bramble, cider)",(white wine),0.118307,0.557114,0.103264,0.872845,1.566727,1.0,0.037353,3.483038,0.410264,0.180481,0.712894,0.529100
23,"(french wine, beer)",(white wine),0.068842,0.557114,0.059153,0.859259,1.542341,1.0,0.020800,3.146824,0.377632,0.104363,0.682219,0.482719
48,"(cider, samsung galaxy 10)",(white wine),0.068587,0.557114,0.058899,0.858736,1.541402,1.0,0.020688,3.135169,0.377105,0.103914,0.681038,0.482228
49,"(french wine, dessert wine)",(white wine),0.075217,0.557114,0.064508,0.857627,1.539411,1.0,0.022604,3.110749,0.378901,0.113606,0.678534,0.486708
41,"(cider, dessert wine)",(white wine),0.183835,0.557114,0.157573,0.857143,1.538542,1.0,0.055156,3.100204,0.428876,0.270105,0.677441,0.569990
43,"(french wine, cider)",(white wine),0.093065,0.557114,0.079551,0.854795,1.534327,1.0,0.027704,3.050066,0.383984,0.139410,0.672138,0.498793
30,"(bramble, champagne)",(white wine),0.067313,0.557114,0.057369,0.852273,1.529800,1.0,0.019868,2.997999,0.371314,0.101169,0.666444,0.477624
25,"(cider, black beer)",(white wine),0.081846,0.557114,0.069607,0.850467,1.526560,1.0,0.024010,2.961802,0.375680,0.122257,0.662368,0.487705
51,"(samsung galaxy 10, dessert wine)",(white wine),0.059663,0.557114,0.050739,0.850427,1.526488,1.0,0.017500,2.961011,0.366785,0.089640,0.662278,0.470751
38,"(champagne, dessert wine)",(white wine),0.097144,0.557114,0.082356,0.847769,1.521716,1.0,0.028236,2.909305,0.379737,0.144004,0.656275,0.497798
18,"(beer, champagne)",(white wine),0.090005,0.557114,0.076237,0.847025,1.520382,1.0,0.026094,2.895164,0.376123,0.133542,0.654596,0.491934
47,"(cider, red wine)",(white wine),0.082356,0.557114,0.069352,0.842105,1.511550,1.0,0.023471,2.804946,0.368800,0.121646,0.643487,0.483295
29,"(bluetooth headphones, cider)",(white wine),0.066293,0.557114,0.055584,0.838462,1.505010,1.0,0.018651,2.741677,0.359376,0.097890,0.635260,0.469116
26,"(dessert wine, black beer)",(white wine),0.065528,0.557114,0.054564,0.832685,1.494641,1.0,0.018058,2.647018,0.354150,0.096050,0.622216,0.465313
2,(bramble),(white wine),0.198368,0.557114,0.164202,0.827763,1.485807,1.0,0.053688,2.571385,0.407874,0.277706,0.611104,0.561250
0,(beer),(white wine),0.266191,0.557114,0.218766,0.821839,1.475173,1.0,0.070467,2.485878,0.438961,0.361873,0.597728,0.607258
7,(dessert wine),(white wine),0.310811,0.557114,0.255227,0.821165,1.473963,1.0,0.082070,2.476506,0.466573,0.416563,0.596205,0.639644
6,(cider),(white wine),0.393677,0.557114,0.322794,0.819948,1.471779,1.0,0.103472,2.459771,0.528678,0.514007,0.593458,0.699677
27,"(bluetooth headphones, fresh tuna)",(champagne),0.071137,0.369199,0.056859,0.799283,2.164909,1.0,0.030595,3.142739,0.579296,0.148271,0.681806,0.476644
1,(black beer),(white wine),0.141509,0.557114,0.107343,0.758559,1.361587,1.0,0.028506,1.834342,0.309337,0.181544,0.454846,0.475618
13,(red wine),(white wine),0.150178,0.557114,0.113717,0.757216,1.359176,1.0,0.030051,1.824196,0.310960,0.191581,0.451813,0.480667
15,(samsung galaxy 10),(white wine),0.132585,0.557114,0.099949,0.753846,1.353128,1.0,0.026084,1.799226,0.300861,0.169477,0.444205,0.466626
14,(ring light),(white wine),0.093575,0.557114,0.069352,0.741144,1.330329,1.0,0.017221,1.710940,0.273940,0.119298,0.415526,0.432815
11,(half-life: alyx),(white wine),0.072667,0.557114,0.052524,0.722807,1.297414,1.0,0.012040,1.597754,0.247199,0.090989,0.374122,0.408543
12,(phone charger),(white wine),0.098164,0.557114,0.070882,0.722078,1.296105,1.0,0.016194,1.593563,0.253325,0.121291,0.372475,0.424655
5,(spaghetti),(champagne),0.107598,0.369199,0.077002,0.715640,1.938356,1.0,0.037276,2.218315,0.542467,0.192602,0.549207,0.462102
52,"(white wine, beer, champagne)",(cider),0.076237,0.393677,0.054309,0.712375,1.809542,1.0,0.024296,2.108031,0.484295,0.130675,0.525624,0.425164
8,(french wine),(white wine),0.175676,0.557114,0.124936,0.711176,1.276536,1.0,0.027065,1.533410,0.262797,0.205537,0.347859,0.467716
4,(frozen smoothie),(champagne),0.083376,0.369199,0.058389,0.700306,1.896823,1.0,0.027606,2.104814,0.515809,0.148124,0.524899,0.429227
59,"(white wine, champagne, dessert wine)",(cider),0.082356,0.393677,0.056604,0.687307,1.745865,1.0,0.024182,1.939034,0.465560,0.134954,0.484279,0.415544
39,"(french wine, dessert wine)",(cider),0.075217,0.393677,0.050484,0.671186,1.704918,1.0,0.020873,1.843973,0.447090,0.120658,0.457693,0.399712
31,"(bramble, dessert wine)",(cider),0.092555,0.393677,0.060683,0.655647,1.665446,1.0,0.024247,1.760763,0.440313,0.142600,0.432064,0.404896
35,"(champagne, dessert wine)",(cider),0.097144,0.393677,0.063488,0.653543,1.660102,1.0,0.025245,1.750070,0.440411,0.148568,0.428594,0.407406
57,"(bramble, white wine, dessert wine)",(cider),0.081846,0.393677,0.053289,0.651090,1.653871,1.0,0.021068,1.737766,0.430601,0.126208,0.424548,0.393227
36,"(white wine, champagne)",(cider),0.174401,0.393677,0.113463,0.650585,1.652587,1.0,0.044805,1.735252,0.478305,0.249579,0.423715,0.469399
3,(fresh tuna),(champagne),0.180520,0.369199,0.117287,0.649718,1.759801,1.0,0.050639,1.800834,0.526863,0.271226,0.444702,0.483699
24,"(white wine, black beer)",(cider),0.107343,0.393677,0.069607,0.648456,1.647179,1.0,0.027349,1.724744,0.440148,0.161348,0.420204,0.412635
17,"(beer, champagne)",(cider),0.090005,0.393677,0.058134,0.645892,1.640667,1.0,0.022701,1.712257,0.429114,0.136609,0.415976,0.396780
10,(half-life 2),(white wine),0.081591,0.557114,0.052269,0.640625,1.149900,1.0,0.006814,1.232379,0.141940,0.089130,0.188561,0.367223

Associations with more than 1 item:

In [36]:
frequent_itemsets_2 = apriori(
    dataset_cluster_9_basket, min_support=0.02, use_colnames=True
    )

rules_2 = association_rules(frequent_itemsets_2,
                                  metric="confidence",
                                  min_threshold=0.2, num_itemsets=100)

rules_2.sort_values(by='lift', ascending=False).head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
203,(energy drink),(pancakes),0.087965,0.072922,0.034421,0.391304,5.366069,1.0,0.028007,1.523057,0.892119,0.272177,0.343426,0.431666
204,(pancakes),(energy drink),0.072922,0.087965,0.034421,0.472028,5.366069,1.0,0.028007,1.727430,0.877643,0.272177,0.421105,0.431666
16,(barbecue sauce),(oil),0.045895,0.089495,0.020908,0.455556,5.090282,1.0,0.016800,1.672356,0.842200,0.182628,0.402041,0.344587
17,(oil),(barbecue sauce),0.089495,0.045895,0.020908,0.233618,5.090282,1.0,0.016800,1.244947,0.882529,0.182628,0.196753,0.344587
1032,"(champagne, spaghetti)","(bluetooth headphones, fresh tuna)",0.077002,0.071137,0.026517,0.344371,4.840941,1.0,0.021039,1.416750,0.859621,0.218029,0.294159,0.358565
1029,"(bluetooth headphones, fresh tuna)","(champagne, spaghetti)",0.071137,0.077002,0.026517,0.372760,4.840941,1.0,0.021039,1.471523,0.854194,0.218029,0.320432,0.358565
1031,"(fresh tuna, champagne)","(bluetooth headphones, spaghetti)",0.117287,0.046915,0.026517,0.226087,4.819093,1.0,0.021015,1.231515,0.897791,0.192593,0.187992,0.395652
1030,"(bluetooth headphones, spaghetti)","(fresh tuna, champagne)",0.046915,0.117287,0.026517,0.565217,4.819093,1.0,0.021015,2.030240,0.831502,0.192593,0.507447,0.395652
205,(protein bar),(energy drink),0.066293,0.087965,0.025752,0.388462,4.416076,1.0,0.019921,1.491377,0.828477,0.200397,0.329479,0.340608
206,(energy drink),(protein bar),0.087965,0.066293,0.025752,0.292754,4.416076,1.0,0.019921,1.320201,0.848164,0.200397,0.242540,0.340608

------

Entire dataset, without any cluster specified:

In [37]:
te = TransactionEncoder()
te_fit = te.fit(dataset_basket['list_of_goods']).transform(dataset_basket['list_of_goods'])
dataset_basket = pd.DataFrame(te_fit, columns=te.columns_)

frequent_itemsets = apriori(dataset_basket, min_support=0.05, use_colnames=True)
display(frequent_itemsets.sort_values(by='support', ascending=False))

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6, num_itemsets=100)
rules = rules.sort_values(by='confidence', ascending=False)

display(rules.head(50).sort_values(by='confidence', ascending=False))



frequent_itemsets_2 = apriori(
    dataset_basket, min_support=0.02, use_colnames=True
    )


rules_2 = association_rules(frequent_itemsets_2,
                                  metric="confidence",
                                  min_threshold=0.2, num_itemsets=100)

rules_2.sort_values(by='lift', ascending=False).head(10)

    support             itemsets
43  0.34900                (oil)
17  0.25052        (cooking oil)
3   0.18067        (babies food)
1   0.15952          (asparagus)
8   0.15134               (cake)
..      ...                  ...
56  0.05175      (strong cheese)
47  0.05157      (pokemon sword)
76  0.05071       (chicken, oil)
53  0.05018  (samsung galaxy 10)
11  0.05002            (cereals)

[86 rows x 2 columns]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
12,"(cooking oil, cake)",(oil),0.07009,0.34900,0.05754,0.820944,2.352277,1.0,0.033079,3.635744,0.618210,0.159148,0.724953,0.492908
2,(barbecue sauce),(oil),0.10281,0.34900,0.07766,0.755374,2.164395,1.0,0.041779,2.661205,0.599625,0.207564,0.624230,0.488948
11,(tea),(oil),0.10951,0.34900,0.07785,0.710894,2.036946,1.0,0.039631,2.251769,0.571673,0.204513,0.555905,0.466980
3,(cake),(oil),0.15134,0.34900,0.10709,0.707612,2.027542,1.0,0.054272,2.226494,0.597167,0.272320,0.550863,0.507230
4,(candy bars),(oil),0.12091,0.34900,0.08261,0.683235,1.957695,1.0,0.040412,2.055154,0.556479,0.213297,0.513419,0.459970
1,(ratchet & clank),(babies food),0.12179,0.18067,0.08237,0.676328,3.743444,1.0,0.060366,2.531360,0.834500,0.374256,0.604955,0.566121
0,(minecraft),(babies food),0.09558,0.18067,0.06423,0.672003,3.719502,1.0,0.046962,2.497976,0.808415,0.302943,0.599676,0.513756
7,(deodorant),(oil),0.08160,0.34900,0.05317,0.651593,1.867029,1.0,0.024692,1.868505,0.505651,0.140874,0.464813,0.401971
6,(cologne),(oil),0.10567,0.34900,0.06737,0.637551,1.826793,1.0,0.030491,1.796114,0.506069,0.173948,0.443242,0.415294
8,(gums),(oil),0.08729,0.34900,0.05553,0.636155,1.822795,1.0,0.025066,1.789225,0.494562,0.145840,0.441099,0.397634
5,(chicken),(oil),0.08093,0.34900,0.05071,0.626591,1.795389,1.0,0.022465,1.743396,0.482028,0.133722,0.426407,0.385946
9,(napkins),(oil),0.09845,0.34900,0.06050,0.614525,1.760817,1.0,0.026141,1.688826,0.479266,0.156351,0.407873,0.393939
10,(soup),(oil),0.08847,0.34900,0.05373,0.607325,1.740185,1.0,0.022854,1.657858,0.466631,0.140017,0.396812,0.380639

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
146,(pancakes),(energy drink),0.06762,0.08550,0.03932,0.581485,6.800991,1.0,0.033538,2.185106,0.914823,0.345518,0.542356,0.520684
145,(energy drink),(pancakes),0.08550,0.06762,0.03932,0.459883,6.800991,1.0,0.033538,1.726256,0.932709,0.345518,0.420712,0.520684
108,(cider),(white wine),0.06388,0.08212,0.03524,0.551659,6.717722,1.0,0.029994,2.047283,0.909221,0.318165,0.511548,0.490394
107,(white wine),(cider),0.08212,0.06388,0.03524,0.429128,6.717722,1.0,0.029994,1.639807,0.927289,0.318165,0.390172,0.490394
140,(dessert wine),(white wine),0.05475,0.08212,0.02735,0.499543,6.083090,1.0,0.022854,1.834085,0.884009,0.249726,0.454769,0.416296
139,(white wine),(dessert wine),0.08212,0.05475,0.02735,0.333049,6.083090,1.0,0.022854,1.417271,0.910369,0.249726,0.294419,0.416296
276,"(bluetooth headphones, fresh tuna)",(champagne),0.03762,0.14195,0.03102,0.824561,5.808816,1.0,0.025680,4.890885,0.860209,0.208819,0.795538,0.521545
279,(champagne),"(bluetooth headphones, fresh tuna)",0.14195,0.03762,0.03102,0.218528,5.808816,1.0,0.025680,1.231496,0.964801,0.208819,0.187979,0.521545
334,"(fresh tuna, frozen smoothie)",(champagne),0.02528,0.14195,0.02084,0.824367,5.807447,1.0,0.017252,4.885474,0.849277,0.142359,0.795312,0.485590
147,(protein bar),(energy drink),0.06100,0.08550,0.03018,0.494754,5.786598,1.0,0.024964,1.810010,0.880923,0.259457,0.447517,0.423868

-----

## **Cupons  and Promotions Strategy**

Based on the customer segmentation and association rules analysis, the following targeted coupon and promotion strategies are proposed to enhance customer engagement and sales:

- `Buy 1, Get 1 Free on Oil`: Many clusters frequently purchase oil, making it the top product for promotional offers.

- `10% Discount on Mixed Vegetables`: Customers buying four different vegetables receive a 10% discount, supporting the “Vegan People” cluster.

- `Monthly 20% Discount on Selected Vegetables`: Each month, a different vegetable is offered at 20% off, encouraging repeat purchases and appealing to vegan customers.

- `Student Card Discount on Alcoholic Beverages`: Students receive a 30% discount on alcoholic drinks purchases over €20, targeting the “University Low-Spenders” segment.

- `15% Discount on Combined Purchases of Energy Drinks and Protein Bars`: This promotion supports the “Tech-Gamer Customers” who tend to buy these products together.

- `10% Discount on Ratchet & Clank Bundle`: Customers buying Ratchet & Clank with Ratchet & Clank 2 get a 10% discount, targeting the “Big Family” cluster.

- `Energy Drink and Pancake Packs`: Bundled promotions for energy drinks and pancakes, reflecting popular joint purchases.

- `Loyalty Card Birthday Gift`: Customers holding a loyalty card receive a birthday cake as a special gift.
------

## **Achievement-Based Incentives**

To further motivate and reward customers, the following achievement-based incentives are suggested:

- `5% Discount on Electronics for Every 25 Energy Drinks Purchased`: Customers in the “Tech-Gamer” cluster receive a 5% discount on electronics each time their total energy drink purchases reach 25, accumulated over time.

- `Champagne Gift for Top Monthly Spenders`: Customers spending the most each month receive two bottles of champagne, rewarding the “High Spenders” cluster.

- `10% Discount on Games for Purchasing 20 Baby Foods`: Supports the “Big Family” cluster by incentivizing baby food purchases.

- `15% Discount on All Purchases After Buying 30 Bottles of Oil`: Encourages overall increased shopping frequency across all customer segments.

These tailored promotions leverage the insights from clustering and association rules, targeting specific customer behaviours to maximize engagement and sales growth.